"use client";

import { BarChart3, Eye, ShoppingBag, DollarSign, TrendingUp } from "lucide-react";

export default function AnalyticsSection() {
  return (
    <div id="section-analytics" className="p-6 bg-[#141414] border border-[#222222] rounded-[24px] space-y-6 shadow-xl">
      <div className="border-b border-[#2A2A2A] pb-3">
        <h3 className="font-editorial text-2xl font-normal text-[#F8F6F3]">
          Product Performance Analytics (Read Only)
        </h3>
        <p className="text-xs text-[#8E8A85]">
          Historical traffic metrics, page views, order conversion velocity, and gross revenue generated by this SKU.
        </p>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <div className="p-4 bg-[#0D0D0D] border border-[#2A2A2A] rounded-[16px] space-y-1">
          <span className="text-[10px] font-bold uppercase text-[#8E8A85]">30d Page Views</span>
          <div className="font-editorial text-2xl font-bold text-[#F8F6F3]">
            14,280 Views
          </div>
          <span className="text-[10px] text-emerald-400 font-mono">+24.5% vs last month</span>
        </div>

        <div className="p-4 bg-[#0D0D0D] border border-[#2A2A2A] rounded-[16px] space-y-1">
          <span className="text-[10px] font-bold uppercase text-[#8E8A85]">Total Orders</span>
          <div className="font-editorial text-2xl font-bold text-emerald-400">
            142 Units Sold
          </div>
          <span className="text-[10px] text-emerald-400 font-mono">14.2% conversion rate</span>
        </div>

        <div className="p-4 bg-[#0D0D0D] border border-[#2A2A2A] rounded-[16px] space-y-1">
          <span className="text-[10px] font-bold uppercase text-[#8E8A85]">Gross Revenue</span>
          <div className="font-editorial text-2xl font-bold text-[#C8A45D]">
            $347,900.00
          </div>
          <span className="text-[10px] text-[#8E8A85] font-mono">Top 5 SKU revenue contributor</span>
        </div>

        <div className="p-4 bg-[#0D0D0D] border border-[#2A2A2A] rounded-[16px] space-y-1">
          <span className="text-[10px] font-bold uppercase text-[#8E8A85]">Top Traffic Channel</span>
          <div className="font-editorial text-xl font-bold text-blue-400">
            Concierge WhatsApp
          </div>
          <span className="text-[10px] text-blue-400 font-mono">45% of total sales</span>
        </div>
      </div>
    </div>
  );
}
