// GOR MENSWEAR — Enterprise B2B & Wholesale Commerce Core Data & Utilities

export const INITIAL_COMPANIES = [
  {
    id: "cmp-01",
    code: "CMP-BIELLA-01",
    name: "Saks Fifth Avenue Luxury Group",
    taxId: "VAT-US-8849102",
    industry: "High-End Department Store",
    tier: "VIP Tier 1",
    creditLimit: 250000,
    outstandingBalance: 68500,
    creditStatus: "Approved",
    paymentTerms: "Net 60",
    assignedSalesRepId: "rep-01",
    assignedSalesRepName: "Dominic Thorne",
    billingAddress: {
      street: "611 5th Ave",
      city: "New York",
      region: "NY",
      country: "United States",
      zip: "10022",
    },
    shippingAddresses: [
      { id: "ship-1", name: "NYC Main Warehouse", street: "100 Hudson St", city: "New York", country: "United States", zip: "10013" },
      { id: "ship-2", name: "Beverly Hills Storefront", street: "9600 Wilshire Blvd", city: "Beverly Hills", country: "United States", zip: "90212" },
    ],
    contacts: [
      { id: "cnt-1", name: "Victoria Sterling", email: "v.sterling@saks.com", phone: "+1 212 555 0140", role: "Company Owner" },
      { id: "cnt-2", name: "Michael Vance", email: "m.vance@saks.com", phone: "+1 212 555 0142", role: "Purchasing Manager" },
      { id: "cnt-3", name: "Elena Rostova", email: "e.rostova@saks.com", phone: "+1 212 555 0145", role: "Finance Manager" },
    ],
    createdAt: "2026-01-15",
  },
  {
    id: "cmp-02",
    code: "CMP-[#090909]-02",
    name: "Harrods Knightsbridge Retail Ltd",
    taxId: "GB-99201481",
    industry: "International Luxury Flagship",
    tier: "VIP Tier 1",
    creditLimit: 300000,
    outstandingBalance: 120000,
    creditStatus: "Approved",
    paymentTerms: "Net 30",
    assignedSalesRepId: "rep-02",
    assignedSalesRepName: "Camilla Vance",
    billingAddress: {
      street: "87-135 Brompton Rd",
      city: "London",
      region: "Greater London",
      country: "United Kingdom",
      zip: "SW1X 7XL",
    },
    shippingAddresses: [
      { id: "ship-3", name: "Thames Fulfillment Hub", street: "Docklands Gate 4", city: "London", country: "United Kingdom", zip: "E14 9SJ" },
    ],
    contacts: [
      { id: "cnt-4", name: "Sir Arthur Pendelton", email: "a.pendelton@harrods.com", phone: "+44 20 7730 1234", role: "Company Owner" },
      { id: "cnt-5", name: "Gideon Cross", email: "g.cross@harrods.com", phone: "+44 20 7730 1238", role: "Purchasing Manager" },
    ],
    createdAt: "2026-02-01",
  },
  {
    id: "cmp-03",
    code: "CMP-[#090909]-03",
    name: "Isetan Shinjuku Menswear Corp",
    taxId: "JP-30194812",
    industry: "APAC Wholesale Distributor",
    tier: "Gold Tier 2",
    creditLimit: 150000,
    outstandingBalance: 34000,
    creditStatus: "Approved",
    paymentTerms: "Net 30",
    assignedSalesRepId: "rep-01",
    assignedSalesRepName: "Dominic Thorne",
    billingAddress: {
      street: "3-14-1 Shinjuku, Shinjuku-ku",
      city: "Tokyo",
      region: "Kanto",
      country: "Japan",
      zip: "160-0022",
    },
    shippingAddresses: [
      { id: "ship-4", name: "Tokyo Bay Logistics Center", street: "Shinagawa Pier 12", city: "Tokyo", country: "Japan", zip: "140-0002" },
    ],
    contacts: [
      { id: "cnt-6", name: "Hiroshi Tanaka", email: "tanaka@isetan.co.jp", phone: "+81 3 3352 1111", role: "Purchasing Manager" },
    ],
    createdAt: "2026-03-10",
  },
  {
    id: "cmp-04",
    code: "CMP-[#090909]-04",
    name: "Printemps Haussmann Paris",
    taxId: "FR-88392014",
    industry: "European Department Boutique",
    tier: "Standard Wholesale",
    creditLimit: 80000,
    outstandingBalance: 82000,
    creditStatus: "Extended",
    paymentTerms: "Net 15",
    assignedSalesRepId: "rep-02",
    assignedSalesRepName: "Camilla Vance",
    billingAddress: {
      street: "64 Boulevard Haussmann",
      city: "Paris",
      region: "Île-de-France",
      country: "France",
      zip: "75009",
    },
    shippingAddresses: [
      { id: "ship-5", name: "Orly Regional Depot", street: "Avenue de l'Europe", city: "Paris", country: "France", zip: "94390" },
    ],
    contacts: [
      { id: "cnt-7", name: "Claire Dubois", email: "c.dubois@printemps.fr", phone: "+33 1 42 82 50 00", role: "Purchasing Manager" },
    ],
    createdAt: "2026-04-18",
  },
];

export const INITIAL_PRICE_LISTS = [
  {
    id: "prc-101",
    name: "Global VIP Tier 1 Contract Price List",
    code: "PRC-VIP-2026",
    currency: "USD",
    effectiveDate: "2026-01-01",
    assignedCompanyCount: 2,
    items: [
      {
        sku: "GOR-CO-ALO-BUR-M",
        productName: "GOR Alo Burgundy Heavyweight Co-Ord",
        msrp: 380,
        wholesalePrice: 190,
        tierPricing: [
          { minQty: 1, maxQty: 50, price: 190 },
          { minQty: 51, maxQty: 200, price: 170 },
          { minQty: 201, maxQty: 9999, price: 150 },
        ],
      },
      {
        sku: "GOR-SH-SILK-IVR-L",
        productName: "Atelier Raw Silk Grandad Shirt",
        msrp: 420,
        wholesalePrice: 210,
        tierPricing: [
          { minQty: 1, maxQty: 50, price: 210 },
          { minQty: 51, maxQty: 200, price: 190 },
          { minQty: 201, maxQty: 9999, price: 175 },
        ],
      },
      {
        sku: "GOR-TR-ONYX-PLE-32",
        productName: "Italian Merino Wool Pleated Trousers",
        msrp: 580,
        wholesalePrice: 290,
        tierPricing: [
          { minQty: 1, maxQty: 50, price: 290 },
          { minQty: 51, maxQty: 200, price: 260 },
          { minQty: 201, maxQty: 9999, price: 235 },
        ],
      },
      {
        sku: "GOR-JK-SHR-AVI-XL",
        productName: "Biella Shearling Trimmed Suede Jacket",
        msrp: 2100,
        wholesalePrice: 1050,
        tierPricing: [
          { minQty: 1, maxQty: 10, price: 1050 },
          { minQty: 11, maxQty: 50, price: 950 },
          { minQty: 51, maxQty: 9999, price: 880 },
        ],
      },
    ],
  },
  {
    id: "prc-102",
    name: "Standard Wholesale Distributor Catalog",
    code: "PRC-STD-2026",
    currency: "USD",
    effectiveDate: "2026-02-15",
    assignedCompanyCount: 8,
    items: [
      {
        sku: "GOR-CO-ALO-BUR-M",
        productName: "GOR Alo Burgundy Heavyweight Co-Ord",
        msrp: 380,
        wholesalePrice: 220,
        tierPricing: [
          { minQty: 1, maxQty: 50, price: 220 },
          { minQty: 51, maxQty: 200, price: 200 },
        ],
      },
      {
        sku: "GOR-SH-SILK-IVR-L",
        productName: "Atelier Raw Silk Grandad Shirt",
        msrp: 420,
        wholesalePrice: 240,
        tierPricing: [
          { minQty: 1, maxQty: 50, price: 240 },
          { minQty: 51, maxQty: 200, price: 220 },
        ],
      },
    ],
  },
];

export const INITIAL_QUOTES = [
  {
    id: "qt-901",
    quoteNumber: "RFQ-2026-8801",
    companyId: "cmp-01",
    companyName: "Saks Fifth Avenue Luxury Group",
    contactName: "Michael Vance",
    contactEmail: "m.vance@saks.com",
    salesRepName: "Dominic Thorne",
    requestedDate: "2026-07-20",
    expirationDate: "2026-08-20",
    status: "Approved",
    discountPercent: 12,
    totalAmount: 48000,
    finalAmount: 42240,
    notes: "Autumn Drop 2026 pre-order with custom embroidered luxury garment bags.",
    lineItems: [
      { sku: "GOR-SH-SILK-IVR-L", productName: "Atelier Raw Silk Grandad Shirt", quantity: 100, listPrice: 420, quotedPrice: 210 },
      { sku: "GOR-JK-SHR-AVI-XL", productName: "Biella Shearling Trimmed Suede Jacket", quantity: 20, listPrice: 2100, quotedPrice: 1050 },
    ],
  },
  {
    id: "qt-902",
    quoteNumber: "RFQ-2026-8802",
    companyId: "cmp-02",
    companyName: "Harrods Knightsbridge Retail Ltd",
    contactName: "Gideon Cross",
    contactEmail: "g.cross@harrods.com",
    salesRepName: "Camilla Vance",
    requestedDate: "2026-07-22",
    expirationDate: "2026-08-22",
    status: "Under Review",
    discountPercent: 15,
    totalAmount: 95000,
    finalAmount: 80750,
    notes: "Knightsbridge Flagship exclusive display shipment.",
    lineItems: [
      { sku: "GOR-TR-ONYX-PLE-32", productName: "Italian Merino Wool Pleated Trousers", quantity: 200, listPrice: 580, quotedPrice: 290 },
      { sku: "GOR-SH-SILK-IVR-L", productName: "Bespoke Silk Monogram Camp Shirt", quantity: 100, listPrice: 390, quotedPrice: 195 },
    ],
  },
  {
    id: "qt-903",
    quoteNumber: "RFQ-2026-8803",
    companyId: "cmp-03",
    companyName: "Isetan Shinjuku Menswear Corp",
    contactName: "Hiroshi Tanaka",
    contactEmail: "tanaka@isetan.co.jp",
    salesRepName: "Dominic Thorne",
    requestedDate: "2026-07-25",
    expirationDate: "2026-08-25",
    status: "Requested",
    discountPercent: 0,
    totalAmount: 28000,
    finalAmount: 28000,
    notes: "Tokyo Ginza showcase restock request.",
    lineItems: [
      { sku: "GOR-CO-ALO-BUR-M", productName: "GOR Alo Burgundy Heavyweight Co-Ord", quantity: 80, listPrice: 380, quotedPrice: 190 },
    ],
  },
];

export const INITIAL_B2B_POS = [
  {
    id: "b2b-po-501",
    poNumber: "B2B-PO-2026-09",
    companyId: "cmp-01",
    companyName: "Saks Fifth Avenue Luxury Group",
    totalAmount: 42240,
    paymentTerms: "Net 60",
    dueDate: "2026-09-20",
    orderDate: "2026-07-21",
    status: "In Production",
    approvalSignoff: { name: "Victoria Sterling (CEO)", date: "2026-07-21" },
    items: [
      { sku: "GOR-SH-SILK-IVR-L", productName: "Atelier Raw Silk Grandad Shirt", orderQty: 100, unitPrice: 210 },
      { sku: "GOR-JK-SHR-AVI-XL", productName: "Biella Shearling Trimmed Suede Jacket", orderQty: 20, unitPrice: 1050 },
    ],
  },
  {
    id: "b2b-po-502",
    poNumber: "B2B-PO-2026-10",
    companyId: "cmp-02",
    companyName: "Harrods Knightsbridge Retail Ltd",
    totalAmount: 68500,
    paymentTerms: "Net 30",
    dueDate: "2026-08-15",
    orderDate: "2026-07-15",
    status: "Shipped",
    approvalSignoff: { name: "Sir Arthur Pendelton", date: "2026-07-15" },
    items: [
      { sku: "GOR-TR-ONYX-PLE-32", productName: "Italian Merino Wool Pleated Trousers", orderQty: 150, unitPrice: 290 },
    ],
  },
  {
    id: "b2b-po-503",
    poNumber: "B2B-PO-2026-08",
    companyId: "cmp-04",
    companyName: "Printemps Haussmann Paris",
    totalAmount: 32000,
    paymentTerms: "Net 15",
    dueDate: "2026-07-10",
    orderDate: "2026-06-25",
    status: "Overdue",
    approvalSignoff: { name: "Claire Dubois", date: "2026-06-25" },
    items: [
      { sku: "GOR-CO-ALO-BUR-M", productName: "GOR Alo Burgundy Heavyweight Co-Ord", orderQty: 100, unitPrice: 220 },
    ],
  },
];

export const INITIAL_SALES_REPS = [
  {
    id: "rep-01",
    code: "REP-DOM-01",
    name: "Dominic Thorne",
    email: "d.thorne@gormenswear.com",
    phone: "+1 212 555 0199",
    region: "North America & APAC",
    portfolioCompanyCount: 14,
    managedRevenue: 1250000,
    commissionRate: 5.5,
    earnedCommission: 68750,
    activityTimeline: [
      { date: "2026-07-26", action: "Revised RFQ-2026-8801 quote discount for Saks Fifth Avenue" },
      { date: "2026-07-22", action: "Conducted virtual buyer presentation for Isetan Shinjuku" },
    ],
  },
  {
    id: "rep-02",
    code: "REP-CAM-02",
    name: "Camilla Vance",
    email: "c.vance@gormenswear.com",
    phone: "+44 20 7946 0888",
    region: "UK & European Union",
    portfolioCompanyCount: 18,
    managedRevenue: 1680000,
    commissionRate: 6.0,
    earnedCommission: 100800,
    activityTimeline: [
      { date: "2026-07-25", action: "Approved Net 30 payment extension for Harrods Knightsbridge" },
      { date: "2026-07-20", action: "Logged on-site atelier review at Printemps Haussmann Paris" },
    ],
  },
];

export const INITIAL_B2B_REPORTS = {
  revenueGrowth: {
    totalWholesaleRevenue: "$4,850,000",
    quarterlyGrowthRate: "+22.4%",
    activeBuyersCount: 34,
    averageB2BAOV: "$38,400",
  },
  quoteConversion: {
    totalRFQCount: 142,
    approvedRFQCount: 118,
    conversionRate: 83.1,
    avgNegotiationDays: 4.2,
  },
  agingPayments: [
    { range: "Current (0-15 Days)", amount: "$145,000", count: 8 },
    { range: "16-30 Days", amount: "$85,000", count: 4 },
    { range: "31-60 Days (Net 60)", amount: "$68,500", count: 2 },
    { range: "60+ Days Overdue", amount: "$32,000", count: 1 },
  ],
};
