// GOR MENSWEAR — Enterprise Connectivity Platform Core Data & Utilities

export const INITIAL_CONNECTIVITY_METRICS = {
  connectedSystemsCount: 24,
  activeConnectionsCount: 22,
  failedConnectionsCount: 2,
  lastSyncTimestamp: "2 minutes ago",
  integrationHealthScore: 98.4,
  syncQueueCount: 12,
};

export const INITIAL_ERP_CONNECTORS = [
  {
    id: "erp-sap",
    code: "CONN-SAP-S4HANA",
    name: "SAP S/4HANA Enterprise ERP",
    category: "ERP",
    status: "Connected",
    environment: "Production",
    lastSync: "5 mins ago",
    healthScore: 99.2,
    endpoint: "https://sap.gormenswear.com/sap/opu/odata/sap/API_BUSINESS_PARTNER",
    description: "Enterprise OData sync for inventory ledger, customer master records, and financial balance sheets.",
  },
  {
    id: "erp-netsuite",
    code: "CONN-NETSUITE",
    name: "Oracle NetSuite ERP & SuiteCommerce",
    category: "ERP",
    status: "Connected",
    environment: "Production",
    lastSync: "12 mins ago",
    healthScore: 98.6,
    endpoint: "https://1234567.restlets.api.netsuite.com/app/site/hosting/restlet.nl",
    description: "SuiteTalk RESTlet sync for sales orders, customer estimates, and purchasing workflows.",
  },
  {
    id: "erp-dynamics",
    code: "CONN-DYNAMICS-365",
    name: "Microsoft Dynamics 365 Supply Chain",
    category: "ERP",
    status: "Degraded",
    environment: "Production",
    lastSync: "45 mins ago",
    healthScore: 84.0,
    endpoint: "https://gormenswear.operations.dynamics.com/data/SalesOrderHeadersV2",
    description: "OData v4 sync for supply chain logistics, warehouse movements, and manufacturing BOMs.",
  },
  {
    id: "erp-odoo",
    code: "CONN-ODOO",
    name: "Odoo Enterprise Community ERP",
    category: "ERP",
    status: "Connected",
    environment: "Sandbox",
    lastSync: "2 hours ago",
    healthScore: 100.0,
    endpoint: "https://odoo-sandbox.gormenswear.com/jsonrpc",
    description: "JSON-RPC endpoint sync for regional inventory staging and supplier purchase orders.",
  },
];

export const INITIAL_POS_CONNECTORS = [
  {
    id: "pos-shopify",
    code: "POS-SHOPIFY-PRO",
    name: "Shopify POS Pro Flagship",
    category: "POS",
    status: "Connected",
    environment: "Production",
    terminalsCount: 14,
    storeLocations: "Mayfair London, Fifth Ave New York, Ginza Tokyo",
    lastSync: "1 min ago",
    healthScore: 100.0,
  },
  {
    id: "pos-square",
    code: "POS-SQUARE-RETAIL",
    name: "Square POS Retail Terminal",
    category: "POS",
    status: "Connected",
    environment: "Production",
    terminalsCount: 8,
    storeLocations: "Paris Haussmann, Milan Quadrilatero",
    lastSync: "3 mins ago",
    healthScore: 99.0,
  },
  {
    id: "pos-clover",
    code: "POS-CLOVER-FLEX",
    name: "Clover POS Flex & Station",
    category: "POS",
    status: "Connected",
    environment: "Production",
    terminalsCount: 6,
    storeLocations: "Zurich Bahnhofstrasse, Dubai Mall",
    lastSync: "10 mins ago",
    healthScore: 97.5,
  },
  {
    id: "pos-custom",
    code: "POS-GOR-ATELIER",
    name: "Custom GOR Atelier POS System",
    category: "POS",
    status: "Connected",
    environment: "Production",
    terminalsCount: 4,
    storeLocations: "Bespoke VIP Private Lounges",
    lastSync: "Real-time",
    healthScore: 100.0,
  },
];

export const INITIAL_ACCOUNTING_CONNECTORS = [
  {
    id: "acct-quickbooks",
    code: "ACCT-QBO-ADVANCED",
    name: "QuickBooks Online Advanced",
    category: "Accounting",
    status: "Connected",
    environment: "Production",
    chartOfAccountsMapped: true,
    lastFinancialSync: "30 mins ago",
    healthScore: 99.5,
  },
  {
    id: "acct-xero",
    code: "ACCT-XERO-GLOBAL",
    name: "Xero Accounting & Invoicing",
    category: "Accounting",
    status: "Connected",
    environment: "Production",
    chartOfAccountsMapped: true,
    lastFinancialSync: "1 hour ago",
    healthScore: 98.8,
  },
  {
    id: "acct-tally",
    code: "ACCT-TALLY-PRIME",
    name: "Tally Prime Enterprise Ledger",
    category: "Accounting",
    status: "Connected",
    environment: "Production",
    chartOfAccountsMapped: true,
    lastFinancialSync: "2 hours ago",
    healthScore: 96.0,
  },
];

export const INITIAL_SHIPPING_CONNECTORS = [
  {
    id: "ship-shiprocket",
    code: "SHIP-SHIPROCKET",
    name: "Shiprocket Express Fulfillment",
    category: "Shipping",
    status: "Connected",
    environment: "Production",
    labelGeneratorActive: true,
    trackingWebhooks: "Active",
    healthScore: 99.0,
  },
  {
    id: "ship-delhivery",
    code: "SHIP-DELHIVERY",
    name: "Delhivery Surface & Air Express",
    category: "Shipping",
    status: "Connected",
    environment: "Production",
    labelGeneratorActive: true,
    trackingWebhooks: "Active",
    healthScore: 98.5,
  },
  {
    id: "ship-bluedart",
    code: "SHIP-BLUEDART",
    name: "Blue Dart Express Courier",
    category: "Shipping",
    status: "Connected",
    environment: "Production",
    labelGeneratorActive: true,
    trackingWebhooks: "Active",
    healthScore: 97.0,
  },
  {
    id: "ship-dhl",
    code: "SHIP-DHL-EXPRESS",
    name: "DHL Express Worldwide",
    category: "Shipping",
    status: "Connected",
    environment: "Production",
    labelGeneratorActive: true,
    trackingWebhooks: "Active",
    healthScore: 100.0,
  },
  {
    id: "ship-fedex",
    code: "SHIP-FEDEX-PRIORITY",
    name: "FedEx International Priority",
    category: "Shipping",
    status: "Connected",
    environment: "Production",
    labelGeneratorActive: true,
    trackingWebhooks: "Active",
    healthScore: 99.2,
  },
];

export const INITIAL_PAYMENT_GATEWAYS = [
  {
    id: "pay-stripe",
    code: "PAY-STRIPE-CONNECT",
    name: "Stripe Payments & Billing",
    category: "Payment",
    status: "Connected",
    environment: "Live",
    webhookStatus: "Active",
    healthScore: 100.0,
  },
  {
    id: "pay-razorpay",
    code: "PAY-RAZORPAY-ENT",
    name: "Razorpay Enterprise Gateway",
    category: "Payment",
    status: "Connected",
    environment: "Live",
    webhookStatus: "Active",
    healthScore: 99.5,
  },
  {
    id: "pay-paypal",
    code: "PAY-PAYPAL-EXPRESS",
    name: "PayPal Express & Braintree",
    category: "Payment",
    status: "Connected",
    environment: "Live",
    webhookStatus: "Active",
    healthScore: 98.0,
  },
];

export const INITIAL_TAX_SERVICES = [
  {
    id: "tax-avalara",
    code: "TAX-AVALARA-AVATAX",
    name: "Avalara AvaTax Real-Time Tax",
    category: "Tax Services",
    status: "Connected",
    environment: "Production",
    realTimeCalculationActive: true,
    healthScore: 100.0,
  },
  {
    id: "tax-taxjar",
    code: "TAX-TAXJAR-AUTO",
    name: "TaxJar Automated Sales Tax",
    category: "Tax Services",
    status: "Connected",
    environment: "Production",
    realTimeCalculationActive: true,
    healthScore: 99.0,
  },
  {
    id: "tax-regional",
    code: "TAX-REGIONAL-GST-VAT",
    name: "Regional GST / VAT Tax Compliance",
    category: "Tax Services",
    status: "Connected",
    environment: "Production",
    realTimeCalculationActive: true,
    healthScore: 98.5,
  },
];

export const INITIAL_WEBHOOK_LOGS = [
  {
    id: "wh-901",
    direction: "Incoming",
    eventType: "order.created",
    source: "Stripe Payments",
    status: "Delivered",
    timestamp: "2026-07-28 10:08:12",
    payloadSnippet: '{"id":"evt_1P8x912","type":"order.created","amount":245000}',
  },
  {
    id: "wh-902",
    direction: "Outgoing",
    eventType: "inventory.updated",
    source: "SAP S/4HANA ERP",
    status: "Delivered",
    timestamp: "2026-07-28 10:04:30",
    payloadSnippet: '{"sku":"GOR-JKT-SUEDE-BIELLA","new_stock":18}',
  },
  {
    id: "wh-903",
    direction: "Outgoing",
    eventType: "shipment.dispatched",
    source: "DHL Express",
    status: "Retrying",
    timestamp: "2026-07-28 09:55:10",
    payloadSnippet: '{"tracking_number":"DHL-99201928","carrier":"DHL"}',
  },
  {
    id: "wh-904",
    direction: "Incoming",
    eventType: "customer.updated",
    source: "Shopify POS Pro",
    status: "Failed",
    timestamp: "2026-07-28 09:30:15",
    payloadSnippet: '{"customer_id":"cust_8812","error":"Schema validation failed"}',
  },
];

export const INITIAL_API_KEYS = [
  {
    id: "key-101",
    keyName: "SAP ERP OData Primary Client",
    prefix: "gor_live_sap_8f912...",
    keyType: "REST API Key",
    createdDate: "2026-01-15",
    lastUsed: "Just now",
    rateLimit: "10,000 req/min",
    status: "Active",
  },
  {
    id: "key-102",
    keyName: "Stripe Live Webhook Secret",
    prefix: "whsec_live_99a81...",
    keyType: "Webhook Secret",
    createdDate: "2026-02-01",
    lastUsed: "2 mins ago",
    rateLimit: "Unlimited",
    status: "Active",
  },
  {
    id: "key-103",
    keyName: "GraphQL Partner Storefront Token",
    prefix: "gor_gql_partner_7721...",
    keyType: "GraphQL Token",
    createdDate: "2026-03-10",
    lastUsed: "12 mins ago",
    rateLimit: "5,000 req/min",
    status: "Active",
  },
  {
    id: "key-104",
    keyName: "NetSuite SuiteTalk OAuth Client",
    prefix: "gor_oa_netsuite_1102...",
    keyType: "OAuth Client",
    createdDate: "2026-04-20",
    lastUsed: "45 mins ago",
    rateLimit: "2,500 req/min",
    status: "Active",
  },
];

export const INITIAL_SYNC_JOBS = [
  {
    id: "job-301",
    jobName: "SAP Customer Master Ledger Sync",
    sourceSystem: "SAP S/4HANA",
    targetSystem: "GOR Customer CRM",
    status: "Success",
    itemsProcessed: 1450,
    timestamp: "2026-07-28 10:05:00",
    errorDetails: "None",
  },
  {
    id: "job-302",
    jobName: "Omnichannel POS Inventory Balance Sync",
    sourceSystem: "Shopify POS Pro",
    targetSystem: "GOR Enterprise WMS",
    status: "Success",
    itemsProcessed: 840,
    timestamp: "2026-07-28 10:00:00",
    errorDetails: "None",
  },
  {
    id: "job-303",
    jobName: "Dynamics 365 BOM Stock Reconciliation",
    sourceSystem: "Microsoft Dynamics 365",
    targetSystem: "GOR Catalog",
    status: "Failed",
    itemsProcessed: 12,
    timestamp: "2026-07-28 09:45:00",
    errorDetails: "Timeout waiting for OData response from Dynamics 365 gateway.",
  },
];

export const INITIAL_SYSTEM_HEALTH = {
  apiResponseTime: "42 ms",
  errorRate: "0.04%",
  integrationUptime: "99.98%",
  serviceAvailability: [
    { service: "ERP Connector Gateway", status: "Operational", responseTime: "38 ms" },
    { service: "POS Terminal Real-Time Sync", status: "Operational", responseTime: "24 ms" },
    { service: "Logistics Carrier Webhook Receiver", status: "Operational", responseTime: "45 ms" },
    { service: "Stripe & Razorpay Payment Webhooks", status: "Operational", responseTime: "18 ms" },
    { service: "Avalara Tax Engine", status: "Operational", responseTime: "62 ms" },
    { service: "Dynamics 365 OData Gateway", status: "Degraded", responseTime: "340 ms" },
  ],
};
