// GOR MENSWEAR — Enterprise Digital Asset Management (DAM) Core Data

export const INITIAL_DAM_METRICS = {
  totalAssetsCount: 1480,
  storageUsedFormatted: "42.8 GB / 500 GB",
  recentlyUploadedCount: 24,
  pendingApprovalsCount: 6,
  expiringAssetsCount: 3,
  aiTaggedAssetsCount: 1410,
};

export const INITIAL_DAM_ASSETS = [
  {
    id: "asset-101",
    name: "Biella Shearling Trimmed Suede Jacket — Hero Studio Shot",
    fileType: "Image",
    folder: "Products/Outerwear",
    resolution: "3840 x 2160 (4K UHD)",
    fileSize: "4.2 MB",
    status: "Approved",
    version: "v2.0",
    aiTags: ["Outerwear", "Suede", "Shearling", "Atelier", "Studio Capture"],
    copyright: "© 2026 GOR Atelier Limited",
    photographer: "Marco Bellini (Milan Studio)",
    usageRights: "Worldwide Commercial & Digital Media Rights",
    expirationDate: "2028-12-31",
    usageCount: 142,
    usedInProducts: ["Biella Shearling Trimmed Suede Jacket"],
    usedInCMS: ["Homepage Hero Carousel", "Outerwear Category Banner"],
    imageUrl: "/images/products/shearling-jacket.jpg",
    uploadedAt: "2026-07-28 09:30",
  },
  {
    id: "asset-102",
    name: "Italian Merino Wool Pleated Trousers — Savile Drape",
    fileType: "Image",
    folder: "Products/Trousers",
    resolution: "3840 x 2160 (4K UHD)",
    fileSize: "3.8 MB",
    status: "Approved",
    version: "v1.2",
    aiTags: ["Trousers", "Merino Wool", "Savile Row", "Pleated"],
    copyright: "© 2026 GOR Atelier Limited",
    photographer: "Antoine Laurent (Paris)",
    usageRights: "Worldwide Digital & Print License",
    expirationDate: "2027-06-30",
    usageCount: 98,
    usedInProducts: ["Italian Merino Wool Pleated Trousers"],
    usedInCMS: ["Lookbook 2026 Grid"],
    imageUrl: "/images/products/pleated-trousers.jpg",
    uploadedAt: "2026-07-27 14:15",
  },
  {
    id: "asset-103",
    name: "Atelier Raw Silk Grandad Shirt — Kyoto Weave High-Res",
    fileType: "Image",
    folder: "Products/Shirts",
    resolution: "4096 x 2304 (4K Cinema)",
    fileSize: "5.1 MB",
    status: "In Review",
    version: "v1.0",
    aiTags: ["Shirt", "Raw Silk", "Kyoto Weave", "Grandad Collar"],
    copyright: "© 2026 GOR Atelier Limited",
    photographer: "Kenji Sato (Tokyo)",
    usageRights: "Worldwide Commercial License",
    expirationDate: "2029-01-01",
    usageCount: 45,
    usedInProducts: ["Atelier Heavyweight Raw Silk Grandad Shirt"],
    usedInCMS: ["New Arrivals Section"],
    imageUrl: "/images/products/silk-shirt.jpg",
    uploadedAt: "2026-07-28 10:00",
  },
  {
    id: "asset-104",
    name: "GOR Menswear Primary Brand Crest & Monogram Vector",
    fileType: "Logo",
    folder: "Brand-Assets",
    resolution: "Vector SVG / EPS 300 DPI",
    fileSize: "1.2 MB",
    status: "Approved",
    version: "v3.0",
    aiTags: ["Logo", "Brand Crest", "Monogram", "Gold Foil"],
    copyright: "© 2026 GOR Menswear IP Holdings",
    photographer: "Internal Brand Identity Team",
    usageRights: "Unlimited Global Franchise Rights",
    expirationDate: "Never",
    usageCount: 840,
    usedInProducts: ["All Catalog Products"],
    usedInCMS: ["Global Header Navbar", "Invoice PDF Header"],
    imageUrl: "/images/logo.png",
    uploadedAt: "2026-01-01 00:00",
  },
  {
    id: "asset-105",
    name: "Autumn 2026 Lookbook & Bespoke Crafting PDF Guide",
    fileType: "PDF",
    folder: "Campaigns/Autumn-2026",
    resolution: "PDF Vector Print Ready",
    fileSize: "18.4 MB",
    status: "Approved",
    version: "v1.0",
    aiTags: ["PDF", "Lookbook", "Campaign", "Bespoke Guide"],
    copyright: "© 2026 GOR Atelier Limited",
    photographer: "GOR Editorial Team",
    usageRights: "Public Editorial & Press Release License",
    expirationDate: "2026-12-31",
    usageCount: 312,
    usedInProducts: ["VIP Member Downloads"],
    usedInCMS: ["Press & Media Room"],
    imageUrl: "/images/products/camp-shirt.jpg",
    uploadedAt: "2026-07-20 11:00",
  },
];

export const INITIAL_DAM_FOLDERS = [
  { id: "f-01", name: "Products/Outerwear", path: "Products/Outerwear", count: 240, icon: "Folder" },
  { id: "f-02", name: "Products/Shirts", path: "Products/Shirts", count: 320, icon: "Folder" },
  { id: "f-03", name: "Products/Trousers", path: "Products/Trousers", count: 180, icon: "Folder" },
  { id: "f-04", name: "Campaigns/Autumn-2026", path: "Campaigns/Autumn-2026", count: 450, icon: "Folder" },
  { id: "f-05", name: "Brand-Assets", path: "Brand-Assets", count: 190, icon: "Folder" },
  { id: "f-06", name: "Archive & Trash", path: "Archive", count: 100, icon: "Trash2" },
];

export const INITIAL_DAM_VERSIONS = [
  {
    version: "v2.0",
    status: "Current Active",
    modifiedAt: "2026-07-28 09:30",
    modifiedBy: "Marco Bellini",
    notes: "High-contrast Studio lighting update with WebP compression.",
  },
  {
    version: "v1.1",
    status: "Archived",
    modifiedAt: "2026-06-15 11:00",
    modifiedBy: "Sarah Jenkins",
    notes: "Color balance adjusted for Mayfair print lookbook.",
  },
  {
    version: "v1.0",
    status: "Original RAW",
    modifiedAt: "2026-05-01 14:00",
    modifiedBy: "Marco Bellini",
    notes: "Original Hasselblad 100MP RAW camera capture.",
  },
];

export const INITIAL_APPROVAL_QUEUE = [
  {
    id: "appr-501",
    assetName: "Atelier Raw Silk Grandad Shirt — Kyoto Weave High-Res",
    submittedBy: "Kenji Sato (Tokyo Photographer)",
    reviewer: "Marcus Sterling (Brand Director)",
    status: "In Review",
    submittedAt: "2026-07-28 10:00",
    comment: "Check color saturation on golden thread weave.",
  },
  {
    id: "appr-502",
    assetName: "Bespoke Silk Monogram Camp Shirt Campaign Video",
    submittedBy: "Video Production Team",
    reviewer: "Marcus Sterling (Brand Director)",
    status: "In Review",
    submittedAt: "2026-07-28 08:30",
    comment: "4K 60fps MP4 video preview generation complete.",
  },
];

export const INITIAL_DAM_ANALYTICS = {
  storageByType: [
    { type: "Images (4K/WebP)", usageGB: 28.4, percentage: "66.3%" },
    { type: "Videos (MP4 4K)", usageGB: 11.2, percentage: "26.1%" },
    { type: "PDFs & Documents", usageGB: 3.2, percentage: "7.6%" },
  ],
  topDownloaded: [
    { name: "GOR Brand Crest Logo Vector", downloads: 840 },
    { name: "Autumn 2026 Lookbook PDF", downloads: 312 },
    { name: "Shearling Suede Jacket Hero", downloads: 142 },
  ],
};
