// GOR MENSWEAR — 35 Verified Real Products Data
// Reclassified by actual garment type:
// - Polos: 21 products (16 luxury knit/zip polos + 5 mesh polos)
// - T-Shirts: 6 products (graphic & fine-knit crewneck tees)
// - Shirts: 4 products (pleated & crochet button-down shirts)
// - Jackets: 1 product (short-sleeve zip bomber overshirt)
// - Jerseys: 3 products (Los Angeles #13 mesh athletic jerseys)

export const REAL_PRODUCTS_CATALOG = [
  // =========================================================================
  // CATEGORY: POLOS (21 PRODUCTS)
  // =========================================================================
  {
    id: "gor-casablanca-mint-green-zip-polo",
    name: "GOR Casablanca Mint Green Textured Zip Polo",
    slug: "gor-casablanca-mint-green-zip-polo",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-premium",
    subcategory: "Premium",
    subcategorySlug: "premium",
    price: 1999,
    compareAtPrice: 2499,
    costPerItem: 900,
    stock: 16,
    minStockThreshold: 5,
    sku: "GOR-POL-CSM-16",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Mint Green"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 21.png",
    image: "/images/categories/t-shirts/image copy 21.png",
    images: ["/images/categories/t-shirts/image copy 21.png"],
    description: "Mint green textured luxury knit zip polo with vibrant green ribbed trims and chest monogram emblem.",
    tags: ["Polo", "Zip", "Mint Green", "Casablanca"],
    variants: [
      { size: "S", color: "Mint Green", stock: 4, sku: "GOR-POL-CSM-16-S" },
      { size: "M", color: "Mint Green", stock: 6, sku: "GOR-POL-CSM-16-M" },
      { size: "L", color: "Mint Green", stock: 4, sku: "GOR-POL-CSM-16-L" },
      { size: "XL", color: "Mint Green", stock: 2, sku: "GOR-POL-CSM-16-XL" },
    ],
  },
  {
    id: "gor-sage-green-textured-knit-polo",
    name: "GOR Sage Green Waffle Knit Polo",
    slug: "gor-sage-green-waffle-knit-polo",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-premium",
    subcategory: "Premium",
    subcategorySlug: "premium",
    price: 1250,
    compareAtPrice: 1650,
    costPerItem: 550,
    stock: 24,
    minStockThreshold: 5,
    sku: "GOR-POL-SG-01",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Sage Green"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image.png",
    image: "/images/categories/t-shirts/image.png",
    images: ["/images/categories/t-shirts/image.png"],
    description: "Sage green waffle textured luxury knit polo tailored with a refined placket and ribbed trims.",
    tags: ["Polo", "Luxury", "Knit", "Sage Green"],
    variants: [
      { size: "S", color: "Sage Green", stock: 6, sku: "GOR-POL-SG-01-S" },
      { size: "M", color: "Sage Green", stock: 8, sku: "GOR-POL-SG-01-M" },
      { size: "L", color: "Sage Green", stock: 6, sku: "GOR-POL-SG-01-L" },
      { size: "XL", color: "Sage Green", stock: 4, sku: "GOR-POL-SG-01-XL" },
    ],
  },
  {
    id: "gor-boss-striped-luxury-knit-polo",
    name: "GOR BOSS Striped Luxury Knit Polo",
    slug: "gor-boss-striped-luxury-knit-polo",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-basic",
    subcategory: "Basic",
    subcategorySlug: "basic",
    price: 850,
    compareAtPrice: 1100,
    costPerItem: 380,
    stock: 30,
    minStockThreshold: 5,
    sku: "GOR-POL-BSS-02",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Navy / White"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 6.png",
    image: "/images/categories/t-shirts/image copy 6.png",
    images: ["/images/categories/t-shirts/image copy 6.png"],
    description: "Classic horizontal striped short-sleeve knit polo with branded chest logo and contrast ribbed collar.",
    tags: ["Polo", "Striped", "Navy", "Smart Casual"],
    variants: [
      { size: "S", color: "Navy / White", stock: 7, sku: "GOR-POL-BSS-02-S" },
      { size: "M", color: "Navy / White", stock: 10, sku: "GOR-POL-BSS-02-M" },
      { size: "L", color: "Navy / White", stock: 8, sku: "GOR-POL-BSS-02-L" },
      { size: "XL", color: "Navy / White", stock: 5, sku: "GOR-POL-BSS-02-XL" },
    ],
  },
  {
    id: "gor-green-olive-striped-polo-shirt",
    name: "GOR Green Olive Striped Polo Shirt",
    slug: "gor-green-olive-striped-polo-shirt",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-basic",
    subcategory: "Basic",
    subcategorySlug: "basic",
    price: 850,
    compareAtPrice: 1100,
    costPerItem: 380,
    stock: 30,
    minStockThreshold: 5,
    sku: "GOR-POL-OLV-03",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Olive Green"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 7.png",
    image: "/images/categories/t-shirts/image copy 7.png",
    images: ["/images/categories/t-shirts/image copy 7.png"],
    description: "Earth-toned olive green and white horizontal striped casual polo shirt with spread collar.",
    tags: ["Polo", "Striped", "Olive", "Casual"],
    variants: [
      { size: "S", color: "Olive Green", stock: 7, sku: "GOR-POL-OLV-03-S" },
      { size: "M", color: "Olive Green", stock: 10, sku: "GOR-POL-OLV-03-M" },
      { size: "L", color: "Olive Green", stock: 8, sku: "GOR-POL-OLV-03-L" },
      { size: "XL", color: "Olive Green", stock: 5, sku: "GOR-POL-OLV-03-XL" },
    ],
  },
  {
    id: "gor-dark-grey-geometric-linear-knit-polo",
    name: "GOR Dark Grey Geometric Linear Knit Polo",
    slug: "gor-dark-grey-geometric-linear-knit-polo",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-premium",
    subcategory: "Premium",
    subcategorySlug: "premium",
    price: 1250,
    compareAtPrice: 1650,
    costPerItem: 550,
    stock: 24,
    minStockThreshold: 5,
    sku: "GOR-POL-GRY-04",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Dark Grey"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 8.png",
    image: "/images/categories/t-shirts/image copy 8.png",
    images: ["/images/categories/t-shirts/image copy 8.png"],
    description: "Dark grey modern polo shirt with fine linear geometric weave pattern and tailored placket.",
    tags: ["Polo", "Linear", "Textured", "Dark Grey"],
    variants: [
      { size: "S", color: "Dark Grey", stock: 6, sku: "GOR-POL-GRY-04-S" },
      { size: "M", color: "Dark Grey", stock: 8, sku: "GOR-POL-GRY-04-M" },
      { size: "L", color: "Dark Grey", stock: 6, sku: "GOR-POL-GRY-04-L" },
      { size: "XL", color: "Dark Grey", stock: 4, sku: "GOR-POL-GRY-04-XL" },
    ],
  },
  {
    id: "gor-sage-green-luxury-knit-polo-edition-2",
    name: "GOR Sage Green Luxury Knit Polo (Edition II)",
    slug: "gor-sage-green-luxury-knit-polo-edition-2",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-premium",
    subcategory: "Premium",
    subcategorySlug: "premium",
    price: 1250,
    compareAtPrice: 1650,
    costPerItem: 550,
    stock: 20,
    minStockThreshold: 5,
    sku: "GOR-POL-SG2-05",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Sage Green"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 9.png",
    image: "/images/categories/t-shirts/image copy 9.png",
    images: ["/images/categories/t-shirts/image copy 9.png"],
    description: "Alternate angle cut of the signature sage green luxury knit polo shirt with woven placket detail.",
    tags: ["Polo", "Luxury", "Knit", "Sage Green"],
    variants: [
      { size: "S", color: "Sage Green", stock: 5, sku: "GOR-POL-SG2-05-S" },
      { size: "M", color: "Sage Green", stock: 7, sku: "GOR-POL-SG2-05-M" },
      { size: "L", color: "Sage Green", stock: 5, sku: "GOR-POL-SG2-05-L" },
      { size: "XL", color: "Sage Green", stock: 3, sku: "GOR-POL-SG2-05-XL" },
    ],
  },
  {
    id: "gor-light-sage-solid-knit-polo",
    name: "GOR Light Sage Solid Knit Polo",
    slug: "gor-light-sage-solid-knit-polo",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-basic",
    subcategory: "Basic",
    subcategorySlug: "basic",
    price: 1250,
    compareAtPrice: 1650,
    costPerItem: 550,
    stock: 25,
    minStockThreshold: 5,
    sku: "GOR-POL-LSG-06",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Light Sage"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 10.png",
    image: "/images/categories/t-shirts/image copy 10.png",
    images: ["/images/categories/t-shirts/image copy 10.png"],
    description: "Clean light sage pastel short-sleeve polo in smooth stretch mercerized cotton knit.",
    tags: ["Polo", "Pastel", "Solid", "Light Sage"],
    variants: [
      { size: "S", color: "Light Sage", stock: 6, sku: "GOR-POL-LSG-06-S" },
      { size: "M", color: "Light Sage", stock: 9, sku: "GOR-POL-LSG-06-M" },
      { size: "L", color: "Light Sage", stock: 6, sku: "GOR-POL-LSG-06-L" },
      { size: "XL", color: "Light Sage", stock: 4, sku: "GOR-POL-LSG-06-XL" },
    ],
  },
  {
    id: "gor-white-textured-khaki-collar-polo",
    name: "GOR White Textured Khaki Collar Tipped Polo",
    slug: "gor-white-textured-khaki-collar-polo",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-premium",
    subcategory: "Premium",
    subcategorySlug: "premium",
    price: 1250,
    compareAtPrice: 1650,
    costPerItem: 550,
    stock: 24,
    minStockThreshold: 5,
    sku: "GOR-POL-WTK-07",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["White / Khaki"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 11.png",
    image: "/images/categories/t-shirts/image copy 11.png",
    images: ["/images/categories/t-shirts/image copy 11.png"],
    description: "Crisp white textured knit polo accented with a contrast khaki-tan tipping on the collar.",
    tags: ["Polo", "Textured", "White", "Khaki Tipped"],
    variants: [
      { size: "S", color: "White / Khaki", stock: 6, sku: "GOR-POL-WTK-07-S" },
      { size: "M", color: "White / Khaki", stock: 8, sku: "GOR-POL-WTK-07-M" },
      { size: "L", color: "White / Khaki", stock: 6, sku: "GOR-POL-WTK-07-L" },
      { size: "XL", color: "White / Khaki", stock: 4, sku: "GOR-POL-WTK-07-XL" },
    ],
  },
  {
    id: "gor-dg-white-vertical-lettering-polo",
    name: "GOR Dolce & Gabbana White Lettering Polo",
    slug: "gor-dg-white-vertical-lettering-polo",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-graphic",
    subcategory: "Graphic",
    subcategorySlug: "graphic",
    price: 1250,
    compareAtPrice: 1650,
    costPerItem: 550,
    stock: 20,
    minStockThreshold: 5,
    sku: "GOR-POL-DGW-08",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["White"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 12.png",
    image: "/images/categories/t-shirts/image copy 12.png",
    images: ["/images/categories/t-shirts/image copy 12.png"],
    description: "Designer white luxury polo with vertical monochrome branding accent along the placket.",
    tags: ["Polo", "Designer", "Monochrome", "White"],
    variants: [
      { size: "S", color: "White", stock: 5, sku: "GOR-POL-DGW-08-S" },
      { size: "M", color: "White", stock: 7, sku: "GOR-POL-DGW-08-M" },
      { size: "L", color: "White", stock: 5, sku: "GOR-POL-DGW-08-L" },
      { size: "XL", color: "White", stock: 3, sku: "GOR-POL-DGW-08-XL" },
    ],
  },
  {
    id: "gor-dark-olive-piped-placket-polo",
    name: "GOR Dark Olive Piped Placket Luxury Polo",
    slug: "gor-dark-olive-piped-placket-polo",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-premium",
    subcategory: "Premium",
    subcategorySlug: "premium",
    price: 1250,
    compareAtPrice: 1650,
    costPerItem: 550,
    stock: 22,
    minStockThreshold: 5,
    sku: "GOR-POL-OLP-09",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Dark Olive"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 13.png",
    image: "/images/categories/t-shirts/image copy 13.png",
    images: ["/images/categories/t-shirts/image copy 13.png"],
    description: "Deep olive green polo shirt detailed with contrast fine piping along the button placket.",
    tags: ["Polo", "Piped", "Dark Olive", "Luxury"],
    variants: [
      { size: "S", color: "Dark Olive", stock: 5, sku: "GOR-POL-OLP-09-S" },
      { size: "M", color: "Dark Olive", stock: 8, sku: "GOR-POL-OLP-09-M" },
      { size: "L", color: "Dark Olive", stock: 6, sku: "GOR-POL-OLP-09-L" },
      { size: "XL", color: "Dark Olive", stock: 3, sku: "GOR-POL-OLP-09-XL" },
    ],
  },
  {
    id: "gor-white-textured-solid-luxury-polo",
    name: "GOR White Textured Solid Luxury Knit Polo",
    slug: "gor-white-textured-solid-luxury-polo",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-basic",
    subcategory: "Basic",
    subcategorySlug: "basic",
    price: 1250,
    compareAtPrice: 1650,
    costPerItem: 550,
    stock: 26,
    minStockThreshold: 5,
    sku: "GOR-POL-WTS-10",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["White"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 14.png",
    image: "/images/categories/t-shirts/image copy 14.png",
    images: ["/images/categories/t-shirts/image copy 14.png"],
    description: "Pristine white tonal textured luxury knit polo with fine pique weave structure.",
    tags: ["Polo", "White", "Solid", "Luxury"],
    variants: [
      { size: "S", color: "White", stock: 6, sku: "GOR-POL-WTS-10-S" },
      { size: "M", color: "White", stock: 9, sku: "GOR-POL-WTS-10-M" },
      { size: "L", color: "White", stock: 7, sku: "GOR-POL-WTS-10-L" },
      { size: "XL", color: "White", stock: 4, sku: "GOR-POL-WTS-10-XL" },
    ],
  },
  {
    id: "gor-khaki-tan-piped-placket-polo",
    name: "GOR Khaki Tan Piped Placket Luxury Polo",
    slug: "gor-khaki-tan-piped-placket-polo",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-premium",
    subcategory: "Premium",
    subcategorySlug: "premium",
    price: 1250,
    compareAtPrice: 1650,
    costPerItem: 550,
    stock: 24,
    minStockThreshold: 5,
    sku: "GOR-POL-KHP-11",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Khaki Tan"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 15.png",
    image: "/images/categories/t-shirts/image copy 15.png",
    images: ["/images/categories/t-shirts/image copy 15.png"],
    description: "Tailored khaki tan short-sleeve polo with tonal contrast piping along the front placket.",
    tags: ["Polo", "Khaki", "Piped", "Smart Casual"],
    variants: [
      { size: "S", color: "Khaki Tan", stock: 6, sku: "GOR-POL-KHP-11-S" },
      { size: "M", color: "Khaki Tan", stock: 8, sku: "GOR-POL-KHP-11-M" },
      { size: "L", color: "Khaki Tan", stock: 6, sku: "GOR-POL-KHP-11-L" },
      { size: "XL", color: "Khaki Tan", stock: 4, sku: "GOR-POL-KHP-11-XL" },
    ],
  },
  {
    id: "gor-charcoal-grey-accent-shoulder-polo",
    name: "GOR Charcoal Grey Accent Shoulder Polo",
    slug: "gor-charcoal-grey-accent-shoulder-polo",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-basic",
    subcategory: "Basic",
    subcategorySlug: "basic",
    price: 1250,
    compareAtPrice: 1650,
    costPerItem: 550,
    stock: 20,
    minStockThreshold: 5,
    sku: "GOR-POL-CHG-12",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Charcoal Grey"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 16.png",
    image: "/images/categories/t-shirts/image copy 16.png",
    images: ["/images/categories/t-shirts/image copy 16.png"],
    description: "Charcoal grey fine-knit polo shirt finished with clean shoulder seam construction and tonal buttons.",
    tags: ["Polo", "Charcoal", "Architectural", "Minimalist"],
    variants: [
      { size: "S", color: "Charcoal Grey", stock: 5, sku: "GOR-POL-CHG-12-S" },
      { size: "M", color: "Charcoal Grey", stock: 7, sku: "GOR-POL-CHG-12-M" },
      { size: "L", color: "Charcoal Grey", stock: 5, sku: "GOR-POL-CHG-12-L" },
      { size: "XL", color: "Charcoal Grey", stock: 3, sku: "GOR-POL-CHG-12-XL" },
    ],
  },
  {
    id: "gor-lv-blue-watercolor-cloud-polo",
    name: "GOR Louis Vuitton Blue Watercolor Cloud Polo",
    slug: "gor-lv-blue-watercolor-cloud-polo",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-graphic",
    subcategory: "Graphic",
    subcategorySlug: "graphic",
    price: 1350,
    compareAtPrice: 1800,
    costPerItem: 600,
    stock: 16,
    minStockThreshold: 5,
    sku: "GOR-POL-LVB-13",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Blue / White"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 17.png",
    image: "/images/categories/t-shirts/image copy 17.png",
    images: ["/images/categories/t-shirts/image copy 17.png"],
    description: "Statement sky blue and white watercolor cloud motif jacquard luxury knit polo shirt.",
    tags: ["Polo", "Watercolor", "Cloud", "Designer"],
    variants: [
      { size: "S", color: "Blue / White", stock: 4, sku: "GOR-POL-LVB-13-S" },
      { size: "M", color: "Blue / White", stock: 6, sku: "GOR-POL-LVB-13-M" },
      { size: "L", color: "Blue / White", stock: 4, sku: "GOR-POL-LVB-13-L" },
      { size: "XL", color: "Blue / White", stock: 2, sku: "GOR-POL-LVB-13-XL" },
    ],
  },
  {
    id: "gor-gucci-cream-monogram-knit-polo",
    name: "GOR Gucci Cream Monogram Jacquard Knit Polo",
    slug: "gor-gucci-cream-monogram-knit-polo",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-graphic",
    subcategory: "Graphic",
    subcategorySlug: "graphic",
    price: 1350,
    compareAtPrice: 1800,
    costPerItem: 600,
    stock: 18,
    minStockThreshold: 5,
    sku: "GOR-POL-GCM-14",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Cream"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 18.png",
    image: "/images/categories/t-shirts/image copy 18.png",
    images: ["/images/categories/t-shirts/image copy 18.png"],
    description: "Sophisticated cream jacquard knit polo shirt with all-over tonal luxury geometric monogram pattern.",
    tags: ["Polo", "Monogram", "Cream", "Jacquard"],
    variants: [
      { size: "S", color: "Cream", stock: 4, sku: "GOR-POL-GCM-14-S" },
      { size: "M", color: "Cream", stock: 6, sku: "GOR-POL-GCM-14-M" },
      { size: "L", color: "Cream", stock: 5, sku: "GOR-POL-GCM-14-L" },
      { size: "XL", color: "Cream", stock: 3, sku: "GOR-POL-GCM-14-XL" },
    ],
  },
  {
    id: "gor-casablanca-cream-textured-zip-polo",
    name: "GOR Casablanca Cream Textured Zip Polo",
    slug: "gor-casablanca-cream-textured-zip-polo",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-premium",
    subcategory: "Premium",
    subcategorySlug: "premium",
    price: 1999,
    compareAtPrice: 2499,
    costPerItem: 900,
    stock: 16,
    minStockThreshold: 5,
    sku: "GOR-POL-CSC-15",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Cream"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 20.png",
    image: "/images/categories/t-shirts/image copy 20.png",
    images: ["/images/categories/t-shirts/image copy 20.png"],
    description: "Textured luxury cream knit zip polo featuring a multi-color striped collar and gold-tone zipper pull.",
    tags: ["Polo", "Zip", "Striped Collar", "Casablanca"],
    variants: [
      { size: "S", color: "Cream", stock: 4, sku: "GOR-POL-CSC-15-S" },
      { size: "M", color: "Cream", stock: 6, sku: "GOR-POL-CSC-15-M" },
      { size: "L", color: "Cream", stock: 4, sku: "GOR-POL-CSC-15-L" },
      { size: "XL", color: "Cream", stock: 2, sku: "GOR-POL-CSC-15-XL" },
    ],
  },
  {
    id: "gor-blue-knit-mesh-3-stripe-polo",
    name: "GOR Blue Knit Mesh 3-Stripe Polo Jersey",
    slug: "gor-blue-knit-mesh-3-stripe-polo",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-premium",
    subcategory: "Premium",
    subcategorySlug: "premium",
    price: 1450,
    compareAtPrice: 1850,
    costPerItem: 650,
    stock: 22,
    minStockThreshold: 5,
    sku: "GOR-POL-3ST-BLU-17",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Royal Blue"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/jerseys/image copy 4.png",
    image: "/images/categories/jerseys/image copy 4.png",
    images: ["/images/categories/jerseys/image copy 4.png"],
    description: "Royal blue breathable knitted mesh polo jersey designed with triple white chest racing stripes.",
    tags: ["Polo", "Mesh", "3-Stripe", "Royal Blue"],
    variants: [
      { size: "S", color: "Royal Blue", stock: 5, sku: "GOR-POL-3ST-BLU-17-S" },
      { size: "M", color: "Royal Blue", stock: 8, sku: "GOR-POL-3ST-BLU-17-M" },
      { size: "L", color: "Royal Blue", stock: 6, sku: "GOR-POL-3ST-BLU-17-L" },
      { size: "XL", color: "Royal Blue", stock: 3, sku: "GOR-POL-3ST-BLU-17-XL" },
    ],
  },
  {
    id: "gor-cream-knit-mesh-3-stripe-polo",
    name: "GOR Cream Knit Mesh 3-Stripe Polo Jersey",
    slug: "gor-cream-knit-mesh-3-stripe-polo",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-premium",
    subcategory: "Premium",
    subcategorySlug: "premium",
    price: 1450,
    compareAtPrice: 1850,
    costPerItem: 650,
    stock: 22,
    minStockThreshold: 5,
    sku: "GOR-POL-3ST-CRM-18",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Cream"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/jerseys/image copy 5.png",
    image: "/images/categories/jerseys/image copy 5.png",
    images: ["/images/categories/jerseys/image copy 5.png"],
    description: "Vintage cream knitted mesh polo jersey detailed with contrast black triple racing stripes.",
    tags: ["Polo", "Mesh", "3-Stripe", "Cream"],
    variants: [
      { size: "S", color: "Cream", stock: 5, sku: "GOR-POL-3ST-CRM-18-S" },
      { size: "M", color: "Cream", stock: 8, sku: "GOR-POL-3ST-CRM-18-M" },
      { size: "L", color: "Cream", stock: 6, sku: "GOR-POL-3ST-CRM-18-L" },
      { size: "XL", color: "Cream", stock: 3, sku: "GOR-POL-3ST-CRM-18-XL" },
    ],
  },
  {
    id: "gor-butter-yellow-knit-mesh-3-stripe-polo",
    name: "GOR Butter Yellow Knit Mesh 3-Stripe Polo Jersey",
    slug: "gor-butter-yellow-knit-mesh-3-stripe-polo",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-premium",
    subcategory: "Premium",
    subcategorySlug: "premium",
    price: 1450,
    compareAtPrice: 1850,
    costPerItem: 650,
    stock: 22,
    minStockThreshold: 5,
    sku: "GOR-POL-3ST-YLW-19",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Butter Yellow"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/jerseys/image copy 6.png",
    image: "/images/categories/jerseys/image copy 6.png",
    images: ["/images/categories/jerseys/image copy 6.png"],
    description: "Soft butter yellow knitted athletic polo jersey featuring triple black chest striping.",
    tags: ["Polo", "Mesh", "3-Stripe", "Butter Yellow"],
    variants: [
      { size: "S", color: "Butter Yellow", stock: 5, sku: "GOR-POL-3ST-YLW-19-S" },
      { size: "M", color: "Butter Yellow", stock: 8, sku: "GOR-POL-3ST-YLW-19-M" },
      { size: "L", color: "Butter Yellow", stock: 6, sku: "GOR-POL-3ST-YLW-19-L" },
      { size: "XL", color: "Butter Yellow", stock: 3, sku: "GOR-POL-3ST-YLW-19-XL" },
    ],
  },
  {
    id: "gor-blue-knit-mesh-3-stripe-polo-alt",
    name: "GOR Blue Knit Mesh 3-Stripe Polo (Alternate View)",
    slug: "gor-blue-knit-mesh-3-stripe-polo-alt",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-premium",
    subcategory: "Premium",
    subcategorySlug: "premium",
    price: 1450,
    compareAtPrice: 1850,
    costPerItem: 650,
    stock: 20,
    minStockThreshold: 5,
    sku: "GOR-POL-3ST-BLU2-20",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Royal Blue"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/jerseys/image copy 7.png",
    image: "/images/categories/jerseys/image copy 7.png",
    images: ["/images/categories/jerseys/image copy 7.png"],
    description: "Alternate perspective of the royal blue knitted mesh polo jersey with triple horizontal stripe styling.",
    tags: ["Polo", "Mesh", "3-Stripe", "Royal Blue"],
    variants: [
      { size: "S", color: "Royal Blue", stock: 5, sku: "GOR-POL-3ST-BLU2-20-S" },
      { size: "M", color: "Royal Blue", stock: 7, sku: "GOR-POL-3ST-BLU2-20-M" },
      { size: "L", color: "Royal Blue", stock: 5, sku: "GOR-POL-3ST-BLU2-20-L" },
      { size: "XL", color: "Royal Blue", stock: 3, sku: "GOR-POL-3ST-BLU2-20-XL" },
    ],
  },
  {
    id: "gor-green-knit-short-sleeve-18-polo-jersey",
    name: "GOR Green Knit Short-Sleeve #18 Polo Jersey",
    slug: "gor-green-knit-short-sleeve-18-polo-jersey",
    categoryId: "cat-polos",
    category: "Polos",
    categorySlug: "polos",
    subcategoryId: "sub-polos-graphic",
    subcategory: "Graphic",
    subcategorySlug: "graphic",
    price: 1450,
    compareAtPrice: 1850,
    costPerItem: 650,
    stock: 24,
    minStockThreshold: 5,
    sku: "GOR-POL-18-GRN-21",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Forest Green"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/jerseys/image copy 8.png",
    image: "/images/categories/jerseys/image copy 8.png",
    images: ["/images/categories/jerseys/image copy 8.png"],
    description: "Forest green luxury fine-knit athletic polo shirt featuring vibrant yellow collegiate #18 chest graphic.",
    tags: ["Polo", "Number 18", "Forest Green", "Collegiate"],
    variants: [
      { size: "S", color: "Forest Green", stock: 6, sku: "GOR-POL-18-GRN-21-S" },
      { size: "M", color: "Forest Green", stock: 8, sku: "GOR-POL-18-GRN-21-M" },
      { size: "L", color: "Forest Green", stock: 6, sku: "GOR-POL-18-GRN-21-L" },
      { size: "XL", color: "Forest Green", stock: 4, sku: "GOR-POL-18-GRN-21-XL" },
    ],
  },

  // =========================================================================
  // CATEGORY: T-SHIRTS (6 REAL PRODUCTS)
  // =========================================================================
  {
    id: "gor-karl-lagerfeld-rhinestone-graphic-tee",
    name: "GOR Karl Lagerfeld Rhinestone Graphic Tee",
    slug: "gor-karl-lagerfeld-rhinestone-graphic-tee",
    categoryId: "cat-tshirts",
    category: "T-Shirts",
    categorySlug: "t-shirts",
    subcategoryId: "sub-tshirts-graphic",
    subcategory: "Graphic / Printed",
    subcategorySlug: "graphic",
    price: 1200,
    compareAtPrice: 1500,
    costPerItem: 500,
    stock: 20,
    minStockThreshold: 5,
    sku: "GOR-TEE-KL-01",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Black"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy.png",
    image: "/images/categories/t-shirts/image copy.png",
    images: ["/images/categories/t-shirts/image copy.png"],
    description: "Signature black graphic tee featuring high-definition rhinestone embellishments and premium combed cotton drape.",
    tags: ["Graphic", "Rhinestone", "Streetwear", "Black"],
    variants: [
      { size: "S", color: "Black", stock: 5, sku: "GOR-TEE-KL-01-S" },
      { size: "M", color: "Black", stock: 6, sku: "GOR-TEE-KL-01-M" },
      { size: "L", color: "Black", stock: 5, sku: "GOR-TEE-KL-01-L" },
      { size: "XL", color: "Black", stock: 4, sku: "GOR-TEE-KL-01-XL" },
    ],
  },
  {
    id: "gor-prada-milano-white-knit-tee",
    name: "GOR Prada Milano White Knit Tee",
    slug: "gor-prada-milano-white-knit-tee",
    categoryId: "cat-tshirts",
    category: "T-Shirts",
    categorySlug: "t-shirts",
    subcategoryId: "sub-tshirts-regular",
    subcategory: "Regular Fit",
    subcategorySlug: "regular-fit",
    price: 1650,
    compareAtPrice: 2200,
    costPerItem: 750,
    stock: 18,
    minStockThreshold: 5,
    sku: "GOR-TEE-PRA-02",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["White"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 2.png",
    image: "/images/categories/t-shirts/image copy 2.png",
    images: ["/images/categories/t-shirts/image copy 2.png"],
    description: "Luxury white fine-knit tee featuring a contrast black collar ring accent and signature Milano chest insignia.",
    tags: ["Luxury", "Knit", "White", "Designer"],
    variants: [
      { size: "S", color: "White", stock: 4, sku: "GOR-TEE-PRA-02-S" },
      { size: "M", color: "White", stock: 6, sku: "GOR-TEE-PRA-02-M" },
      { size: "L", color: "White", stock: 5, sku: "GOR-TEE-PRA-02-L" },
      { size: "XL", color: "White", stock: 3, sku: "GOR-TEE-PRA-02-XL" },
    ],
  },
  {
    id: "gor-chrome-hearts-pink-cross-graphic-tee",
    name: "GOR Chrome Hearts Pink Cross Graphic Tee",
    slug: "gor-chrome-hearts-pink-cross-graphic-tee",
    categoryId: "cat-tshirts",
    category: "T-Shirts",
    categorySlug: "t-shirts",
    subcategoryId: "sub-tshirts-graphic",
    subcategory: "Graphic / Printed",
    subcategorySlug: "graphic",
    price: 1200,
    compareAtPrice: 1500,
    costPerItem: 500,
    stock: 22,
    minStockThreshold: 5,
    sku: "GOR-TEE-CH-PNK-03",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Hot Pink"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 3.png",
    image: "/images/categories/t-shirts/image copy 3.png",
    images: ["/images/categories/t-shirts/image copy 3.png"],
    description: "Vibrant hot pink statement tee with Gothic cross artwork on heavyweight streetwear cotton.",
    tags: ["Graphic", "Cross", "Hot Pink", "Streetwear"],
    variants: [
      { size: "S", color: "Hot Pink", stock: 5, sku: "GOR-TEE-CH-PNK-03-S" },
      { size: "M", color: "Hot Pink", stock: 7, sku: "GOR-TEE-CH-PNK-03-M" },
      { size: "L", color: "Hot Pink", stock: 6, sku: "GOR-TEE-CH-PNK-03-L" },
      { size: "XL", color: "Hot Pink", stock: 4, sku: "GOR-TEE-CH-PNK-03-XL" },
    ],
  },
  {
    id: "gor-chrome-hearts-neon-yellow-cross-tee",
    name: "GOR Chrome Hearts Neon Yellow Cross Graphic Tee",
    slug: "gor-chrome-hearts-neon-yellow-cross-tee",
    categoryId: "cat-tshirts",
    category: "T-Shirts",
    categorySlug: "t-shirts",
    subcategoryId: "sub-tshirts-graphic",
    subcategory: "Graphic / Printed",
    subcategorySlug: "graphic",
    price: 1200,
    compareAtPrice: 1500,
    costPerItem: 500,
    stock: 22,
    minStockThreshold: 5,
    sku: "GOR-TEE-CH-YLW-04",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Neon Yellow"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 4.png",
    image: "/images/categories/t-shirts/image copy 4.png",
    images: ["/images/categories/t-shirts/image copy 4.png"],
    description: "High-voltage neon yellow graphic streetwear tee with signature Gothic cross print.",
    tags: ["Graphic", "Cross", "Neon Yellow", "Streetwear"],
    variants: [
      { size: "S", color: "Neon Yellow", stock: 5, sku: "GOR-TEE-CH-YLW-04-S" },
      { size: "M", color: "Neon Yellow", stock: 7, sku: "GOR-TEE-CH-YLW-04-M" },
      { size: "L", color: "Neon Yellow", stock: 6, sku: "GOR-TEE-CH-YLW-04-L" },
      { size: "XL", color: "Neon Yellow", stock: 4, sku: "GOR-TEE-CH-YLW-04-XL" },
    ],
  },
  {
    id: "gor-black-wolf-graphic-streetwear-tee",
    name: "GOR Black Wolf Graphic Streetwear Tee",
    slug: "gor-black-wolf-graphic-streetwear-tee",
    categoryId: "cat-tshirts",
    category: "T-Shirts",
    categorySlug: "t-shirts",
    subcategoryId: "sub-tshirts-oversized",
    subcategory: "Oversized",
    subcategorySlug: "oversized",
    price: 1200,
    compareAtPrice: 1500,
    costPerItem: 500,
    stock: 25,
    minStockThreshold: 5,
    sku: "GOR-TEE-WLF-05",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Black"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 5.png",
    image: "/images/categories/t-shirts/image copy 5.png",
    images: ["/images/categories/t-shirts/image copy 5.png"],
    description: "Oversized black graphic tee with front wolf print on heavy 260 GSM vintage-washed cotton.",
    tags: ["Oversized", "Graphic", "Wolf", "Streetwear", "Vintage"],
    variants: [
      { size: "S", color: "Black", stock: 6, sku: "GOR-TEE-WLF-05-S" },
      { size: "M", color: "Black", stock: 8, sku: "GOR-TEE-WLF-05-M" },
      { size: "L", color: "Black", stock: 7, sku: "GOR-TEE-WLF-05-L" },
      { size: "XL", color: "Black", stock: 4, sku: "GOR-TEE-WLF-05-XL" },
    ],
  },
  {
    id: "gor-dg-brown-knit-shirt-stripe-collar",
    name: "GOR Dolce & Gabbana Brown DG Knit Shirt",
    slug: "gor-dg-brown-knit-shirt-stripe-collar",
    categoryId: "cat-tshirts",
    category: "T-Shirts",
    categorySlug: "t-shirts",
    subcategoryId: "sub-tshirts-regular",
    subcategory: "Regular Fit",
    subcategorySlug: "regular-fit",
    price: 1450,
    compareAtPrice: 1850,
    costPerItem: 650,
    stock: 20,
    minStockThreshold: 5,
    sku: "GOR-TEE-DG-BRN-06",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Brown"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/jerseys/image copy 3.png",
    image: "/images/categories/jerseys/image copy 3.png",
    images: ["/images/categories/jerseys/image copy 3.png"],
    description: "Earth brown fine-knit crewneck designer tee featuring white stripe ring collar accents and embroidered DG insignia.",
    tags: ["Knit", "Designer", "Brown", "Crewneck"],
    variants: [
      { size: "S", color: "Brown", stock: 5, sku: "GOR-TEE-DG-BRN-06-S" },
      { size: "M", color: "Brown", stock: 7, sku: "GOR-TEE-DG-BRN-06-M" },
      { size: "L", color: "Brown", stock: 5, sku: "GOR-TEE-DG-BRN-06-L" },
      { size: "XL", color: "Brown", stock: 3, sku: "GOR-TEE-DG-BRN-06-XL" },
    ],
  },

  // =========================================================================
  // CATEGORY: SHIRTS (4 REAL PRODUCTS)
  // =========================================================================
  {
    id: "gor-brown-textured-pleated-shirt",
    name: "GOR Brown Textured Pleated Button-Down Shirt",
    slug: "gor-brown-textured-pleated-shirt",
    categoryId: "cat-shirts",
    category: "Shirts",
    categorySlug: "shirts",
    subcategoryId: "sub-shirts-casual",
    subcategory: "Casual",
    subcategorySlug: "casual",
    price: 2150,
    compareAtPrice: 2750,
    costPerItem: 950,
    stock: 18,
    minStockThreshold: 5,
    sku: "GOR-SHT-PLT-BRN-01",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Brown"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/shirts/image.png",
    image: "/images/categories/shirts/image.png",
    images: ["/images/categories/shirts/image.png"],
    description: "Rich chocolate brown micro-pleated button-down short-sleeve shirt with spread collar and relaxed resort silhouette.",
    tags: ["Pleated", "Button-Down", "Brown", "Resort"],
    variants: [
      { size: "S", color: "Brown", stock: 4, sku: "GOR-SHT-PLT-BRN-01-S" },
      { size: "M", color: "Brown", stock: 6, sku: "GOR-SHT-PLT-BRN-01-M" },
      { size: "L", color: "Brown", stock: 5, sku: "GOR-SHT-PLT-BRN-01-L" },
      { size: "XL", color: "Brown", stock: 3, sku: "GOR-SHT-PLT-BRN-01-XL" },
    ],
  },
  {
    id: "gor-green-crochet-open-knit-striped-shirt",
    name: "GOR Green Crochet Open-Knit Striped Shirt",
    slug: "gor-green-crochet-open-knit-striped-shirt",
    categoryId: "cat-shirts",
    category: "Shirts",
    categorySlug: "shirts",
    subcategoryId: "sub-shirts-casual",
    subcategory: "Casual",
    subcategorySlug: "casual",
    price: 2150,
    compareAtPrice: 2750,
    costPerItem: 950,
    stock: 16,
    minStockThreshold: 5,
    sku: "GOR-SHT-CRC-GRN-02",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Forest Green / Cream"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/shirts/image copy.png",
    image: "/images/categories/shirts/image copy.png",
    images: ["/images/categories/shirts/image copy.png"],
    description: "Artisanal open-knit crochet shirt featuring vertical forest green and cream stripes with horn buttons.",
    tags: ["Crochet", "Open Knit", "Striped", "Artisanal"],
    variants: [
      { size: "S", color: "Forest Green / Cream", stock: 4, sku: "GOR-SHT-CRC-GRN-02-S" },
      { size: "M", color: "Forest Green / Cream", stock: 5, sku: "GOR-SHT-CRC-GRN-02-M" },
      { size: "L", color: "Forest Green / Cream", stock: 4, sku: "GOR-SHT-CRC-GRN-02-L" },
      { size: "XL", color: "Forest Green / Cream", stock: 3, sku: "GOR-SHT-CRC-GRN-02-XL" },
    ],
  },
  {
    id: "gor-floral-crochet-open-knit-cardigan-shirt",
    name: "GOR Floral Crochet Open-Knit Cardigan Shirt",
    slug: "gor-floral-crochet-open-knit-cardigan-shirt",
    categoryId: "cat-shirts",
    category: "Shirts",
    categorySlug: "shirts",
    subcategoryId: "sub-shirts-casual",
    subcategory: "Casual",
    subcategorySlug: "casual",
    price: 2150,
    compareAtPrice: 2750,
    costPerItem: 950,
    stock: 14,
    minStockThreshold: 5,
    sku: "GOR-SHT-CRC-FLR-03",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Cream Multi"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/shirts/image copy 2.png",
    image: "/images/categories/shirts/image copy 2.png",
    images: ["/images/categories/shirts/image copy 2.png"],
    description: "Handcrafted cream and multi-color floral crochet open-knit button-down cardigan shirt with scalloped edges.",
    tags: ["Floral", "Crochet", "Cardigan", "Open Knit"],
    variants: [
      { size: "S", color: "Cream Multi", stock: 3, sku: "GOR-SHT-CRC-FLR-03-S" },
      { size: "M", color: "Cream Multi", stock: 5, sku: "GOR-SHT-CRC-FLR-03-M" },
      { size: "L", color: "Cream Multi", stock: 4, sku: "GOR-SHT-CRC-FLR-03-L" },
      { size: "XL", color: "Cream Multi", stock: 2, sku: "GOR-SHT-CRC-FLR-03-XL" },
    ],
  },
  {
    id: "gor-casablanca-bright-green-pleated-shirt",
    name: "GOR Casablanca Bright Green Pleated Shirt",
    slug: "gor-casablanca-bright-green-pleated-shirt",
    categoryId: "cat-shirts",
    category: "Shirts",
    categorySlug: "shirts",
    subcategoryId: "sub-shirts-casual",
    subcategory: "Casual",
    subcategorySlug: "casual",
    price: 2150,
    compareAtPrice: 2750,
    costPerItem: 950,
    stock: 14,
    minStockThreshold: 5,
    sku: "GOR-SHT-CSG-04",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Emerald Green"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 22.png",
    image: "/images/categories/t-shirts/image copy 22.png",
    images: ["/images/categories/t-shirts/image copy 22.png"],
    description: "Bright emerald green pleated luxury short-sleeve shirt crafted from fluid architectural accordion fabric.",
    tags: ["Pleated", "Emerald Green", "Luxury", "Casablanca"],
    variants: [
      { size: "S", color: "Emerald Green", stock: 3, sku: "GOR-SHT-CSG-04-S" },
      { size: "M", color: "Emerald Green", stock: 5, sku: "GOR-SHT-CSG-04-M" },
      { size: "L", color: "Emerald Green", stock: 4, sku: "GOR-SHT-CSG-04-L" },
      { size: "XL", color: "Emerald Green", stock: 2, sku: "GOR-SHT-CSG-04-XL" },
    ],
  },

  // =========================================================================
  // CATEGORY: JACKETS (1 REAL PRODUCT)
  // =========================================================================
  {
    id: "gor-brown-short-sleeve-zip-overshirt",
    name: "GOR Brown Short-Sleeve Zip Bomber Overshirt",
    slug: "gor-brown-short-sleeve-zip-overshirt",
    categoryId: "cat-jackets",
    category: "Jackets",
    categorySlug: "jackets",
    subcategoryId: "sub-jackets-bomber",
    subcategory: "Bomber",
    subcategorySlug: "bomber",
    price: 1650,
    compareAtPrice: 2100,
    costPerItem: 750,
    stock: 15,
    minStockThreshold: 5,
    sku: "GOR-JCK-BRZ-01",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Brown"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/t-shirts/image copy 19.png",
    image: "/images/categories/t-shirts/image copy 19.png",
    images: ["/images/categories/t-shirts/image copy 19.png"],
    description: "Earthy brown technical short-sleeve overshirt with metallic front zip closure and boxy casual drape.",
    tags: ["Jackets", "Bomber", "Zip", "Brown"],
    variants: [
      { size: "S", color: "Brown", stock: 3, sku: "GOR-JCK-BRZ-01-S" },
      { size: "M", color: "Brown", stock: 5, sku: "GOR-JCK-BRZ-01-M" },
      { size: "L", color: "Brown", stock: 4, sku: "GOR-JCK-BRZ-01-L" },
      { size: "XL", color: "Brown", stock: 3, sku: "GOR-JCK-BRZ-01-XL" },
    ],
  },

  // =========================================================================
  // CATEGORY: JERSEYS (3 REAL PRODUCTS)
  // =========================================================================
  {
    id: "gor-los-angeles-13-black-mesh-jersey",
    name: "GOR Los Angeles #13 Black Mesh Athletic Jersey",
    slug: "gor-los-angeles-13-black-mesh-jersey",
    categoryId: "cat-jerseys",
    category: "Jerseys",
    categorySlug: "jerseys",
    subcategoryId: "sub-jerseys-basketball",
    subcategory: "Basketball",
    subcategorySlug: "basketball",
    price: 1350,
    compareAtPrice: 1700,
    costPerItem: 600,
    stock: 25,
    minStockThreshold: 5,
    sku: "GOR-JRS-LA13-BLK-01",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Black"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/jerseys/image.png",
    image: "/images/categories/jerseys/image.png",
    images: ["/images/categories/jerseys/image.png"],
    description: "Heavyweight black breathable mesh basketball jersey featuring white/yellow Los Angeles #13 collegiate lettering.",
    tags: ["Jersey", "Mesh", "Athletic", "Black"],
    variants: [
      { size: "S", color: "Black", stock: 6, sku: "GOR-JRS-LA13-BLK-01-S" },
      { size: "M", color: "Black", stock: 8, sku: "GOR-JRS-LA13-BLK-01-M" },
      { size: "L", color: "Black", stock: 7, sku: "GOR-JRS-LA13-BLK-01-L" },
      { size: "XL", color: "Black", stock: 4, sku: "GOR-JRS-LA13-BLK-01-XL" },
    ],
  },
  {
    id: "gor-los-angeles-13-green-yellow-mesh-jersey",
    name: "GOR Los Angeles #13 Green Yellow Mesh Athletic Jersey",
    slug: "gor-los-angeles-13-green-yellow-mesh-jersey",
    categoryId: "cat-jerseys",
    category: "Jerseys",
    categorySlug: "jerseys",
    subcategoryId: "sub-jerseys-basketball",
    subcategory: "Basketball",
    subcategorySlug: "basketball",
    price: 1350,
    compareAtPrice: 1700,
    costPerItem: 600,
    stock: 25,
    minStockThreshold: 5,
    sku: "GOR-JRS-LA13-GRN-02",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Green / Yellow"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/jerseys/image copy.png",
    image: "/images/categories/jerseys/image copy.png",
    images: ["/images/categories/jerseys/image copy.png"],
    description: "Vibrant kelly green and athletic yellow mesh sports jersey with bold Los Angeles 13 graphics.",
    tags: ["Jersey", "Mesh", "Athletic", "Green Yellow"],
    variants: [
      { size: "S", color: "Green / Yellow", stock: 6, sku: "GOR-JRS-LA13-GRN-02-S" },
      { size: "M", color: "Green / Yellow", stock: 8, sku: "GOR-JRS-LA13-GRN-02-M" },
      { size: "L", color: "Green / Yellow", stock: 7, sku: "GOR-JRS-LA13-GRN-02-L" },
      { size: "XL", color: "Green / Yellow", stock: 4, sku: "GOR-JRS-LA13-GRN-02-XL" },
    ],
  },
  {
    id: "gor-los-angeles-13-cream-green-mesh-jersey",
    name: "GOR Los Angeles #13 Cream Green Mesh Athletic Jersey",
    slug: "gor-los-angeles-13-cream-green-mesh-jersey",
    categoryId: "cat-jerseys",
    category: "Jerseys",
    categorySlug: "jerseys",
    subcategoryId: "sub-jerseys-basketball",
    subcategory: "Basketball",
    subcategorySlug: "basketball",
    price: 1350,
    compareAtPrice: 1700,
    costPerItem: 600,
    stock: 25,
    minStockThreshold: 5,
    sku: "GOR-JRS-LA13-CRM-03",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Cream / Green"],
    sizes: ["S", "M", "L", "XL"],
    imageUrl: "/images/categories/jerseys/image copy 2.png",
    image: "/images/categories/jerseys/image copy 2.png",
    images: ["/images/categories/jerseys/image copy 2.png"],
    description: "Vintage cream and forest green mesh athletic jersey with collegiate ribbed neck and armhole trims.",
    tags: ["Jersey", "Mesh", "Vintage", "Cream Green"],
    variants: [
      { size: "S", color: "Cream / Green", stock: 6, sku: "GOR-JRS-LA13-CRM-03-S" },
      { size: "M", color: "Cream / Green", stock: 8, sku: "GOR-JRS-LA13-CRM-03-M" },
      { size: "L", color: "Cream / Green", stock: 7, sku: "GOR-JRS-LA13-CRM-03-L" },
      { size: "XL", color: "Cream / Green", stock: 4, sku: "GOR-JRS-LA13-CRM-03-XL" },
    ],
  },

  // =========================================================================
  // CATEGORY: PANTS (2 REAL PRODUCTS)
  // =========================================================================
  {
    id: "gor-relaxed-twill-cargo-pants",
    name: "GOR Relaxed Twill Cargo Pants",
    slug: "gor-relaxed-twill-cargo-pants",
    categoryId: "cat-pants",
    category: "Pants",
    categorySlug: "pants",
    subcategoryId: "sub-pants-cargo",
    subcategory: "Cargo",
    subcategorySlug: "cargo",
    price: 1850,
    compareAtPrice: 2250,
    costPerItem: 750,
    stock: 18,
    minStockThreshold: 5,
    sku: "GOR-PNT-CRG-01",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Khaki / Olive"],
    sizes: ["30", "32", "34", "36"],
    imageUrl: "/images/lookbook/image copy 3.png",
    image: "/images/lookbook/image copy 3.png",
    images: ["/images/lookbook/image copy 3.png"],
    description: "Relaxed utility twill cargo pants with functional side bellows pockets and adjustable hem cinches.",
    tags: ["Pants", "Cargo", "Utility", "Twill"],
    variants: [
      { size: "30", color: "Khaki / Olive", stock: 4, sku: "GOR-PNT-CRG-01-30" },
      { size: "32", color: "Khaki / Olive", stock: 6, sku: "GOR-PNT-CRG-01-32" },
      { size: "34", color: "Khaki / Olive", stock: 5, sku: "GOR-PNT-CRG-01-34" },
      { size: "36", color: "Khaki / Olive", stock: 3, sku: "GOR-PNT-CRG-01-36" },
    ],
  },
  {
    id: "gor-pleated-tapered-relaxed-pants",
    name: "GOR Pleated Tapered Relaxed Pants",
    slug: "gor-pleated-tapered-relaxed-pants",
    categoryId: "cat-pants",
    category: "Pants",
    categorySlug: "pants",
    subcategoryId: "sub-pants-relaxed",
    subcategory: "Relaxed",
    subcategorySlug: "relaxed",
    price: 1750,
    compareAtPrice: 2100,
    costPerItem: 700,
    stock: 20,
    minStockThreshold: 5,
    sku: "GOR-PNT-RLX-02",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Charcoal Grey"],
    sizes: ["30", "32", "34", "36"],
    imageUrl: "/images/lookbook/image copy 4.png",
    image: "/images/lookbook/image copy 4.png",
    images: ["/images/lookbook/image copy 4.png"],
    description: "Contemporary relaxed twill pants with single front pleats and a clean tapered ankle break.",
    tags: ["Pants", "Relaxed", "Pleated", "Charcoal"],
    variants: [
      { size: "30", color: "Charcoal Grey", stock: 5, sku: "GOR-PNT-RLX-02-30" },
      { size: "32", color: "Charcoal Grey", stock: 7, sku: "GOR-PNT-RLX-02-32" },
      { size: "34", color: "Charcoal Grey", stock: 5, sku: "GOR-PNT-RLX-02-34" },
      { size: "36", color: "Charcoal Grey", stock: 3, sku: "GOR-PNT-RLX-02-36" },
    ],
  },

  // =========================================================================
  // CATEGORY: TROUSERS (2 REAL PRODUCTS)
  // =========================================================================
  {
    id: "gor-structured-tailored-trousers-charcoal",
    name: "GOR Structured Tailored Pleated Trousers",
    slug: "gor-structured-tailored-trousers-charcoal",
    categoryId: "cat-trousers",
    category: "Trousers",
    categorySlug: "trousers",
    subcategoryId: "sub-trousers-pleated",
    subcategory: "Pleated",
    subcategorySlug: "pleated",
    price: 1950,
    compareAtPrice: 2400,
    costPerItem: 800,
    stock: 16,
    minStockThreshold: 5,
    sku: "GOR-TRS-PLT-01",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Charcoal Slate"],
    sizes: ["30", "32", "34", "36"],
    imageUrl: "/images/lookbook/image copy 5.png",
    image: "/images/lookbook/image copy 5.png",
    images: ["/images/lookbook/image copy 5.png"],
    description: "Sartorial double-pleated trousers with side waist adjusters and architectural fluid drape.",
    tags: ["Trousers", "Pleated", "Tailored", "Sartorial"],
    variants: [
      { size: "30", color: "Charcoal Slate", stock: 4, sku: "GOR-TRS-PLT-01-30" },
      { size: "32", color: "Charcoal Slate", stock: 6, sku: "GOR-TRS-PLT-01-32" },
      { size: "34", color: "Charcoal Slate", stock: 4, sku: "GOR-TRS-PLT-01-34" },
      { size: "36", color: "Charcoal Slate", stock: 2, sku: "GOR-TRS-PLT-01-36" },
    ],
  },
  {
    id: "gor-sartorial-straight-fit-trousers",
    name: "GOR Sartorial Straight-Fit Trousers",
    slug: "gor-sartorial-straight-fit-trousers",
    categoryId: "cat-trousers",
    category: "Trousers",
    categorySlug: "trousers",
    subcategoryId: "sub-trousers-straight",
    subcategory: "Straight Fit",
    subcategorySlug: "straight-fit",
    price: 1850,
    compareAtPrice: 2200,
    costPerItem: 750,
    stock: 14,
    minStockThreshold: 5,
    sku: "GOR-TRS-STR-02",
    status: "Active",
    visibility: "Published",
    isActive: true,
    colors: ["Navy Blue"],
    sizes: ["30", "32", "34", "36"],
    imageUrl: "/images/lookbook/image copy 6.png",
    image: "/images/lookbook/image copy 6.png",
    images: ["/images/lookbook/image copy 6.png"],
    description: "Clean straight-fit wool-blend trousers featuring extended tab closure and sharp central creases.",
    tags: ["Trousers", "Straight Fit", "Navy", "Formal"],
    variants: [
      { size: "30", color: "Navy Blue", stock: 3, sku: "GOR-TRS-STR-02-30" },
      { size: "32", color: "Navy Blue", stock: 5, sku: "GOR-TRS-STR-02-32" },
      { size: "34", color: "Navy Blue", stock: 4, sku: "GOR-TRS-STR-02-34" },
      { size: "36", color: "Navy Blue", stock: 2, sku: "GOR-TRS-STR-02-36" },
    ],
  },
];
