// GOR MENSWEAR — Enterprise Subscription & Membership Commerce Core Data & Utilities

export const INITIAL_SUBSCRIPTION_PLANS = [
  {
    id: "plan-101",
    code: "PLN-[#090909]-MONTHLY",
    name: "Atelier Monthly Silk & Shirting Box",
    interval: "Monthly",
    price: 320,
    currency: "USD",
    discountPercent: 20,
    status: "Active",
    activeSubscribersCount: 240,
    mrrValue: 76800,
    description: "Hand-curated Italian silk shirt delivered every month with bespoke tailoring adjustments.",
    features: [
      "1x Italian Silk/Linen Shirting piece monthly",
      "Complimentary bespoke sleeve alterations",
      "20% off all retail outerwear",
      "Free Express Worldwide Shipping",
    ],
  },
  {
    id: "plan-102",
    code: "PLN-[#090909]-QUARTERLY",
    name: "Savile Wardrobe Quarterly Box",
    interval: "Quarterly",
    price: 850,
    currency: "USD",
    discountPercent: 25,
    status: "Active",
    activeSubscribersCount: 180,
    mrrValue: 51000,
    description: "Seasonal wardrobe update comprising tailored trousers, outerwear layers, and accessories.",
    features: [
      "3-piece seasonal capsule collection",
      "Priority Access to Limited Run Drops",
      "25% Off Storewide Member Discount",
      "Dedicated Private Concierge Stylist",
    ],
  },
  {
    id: "plan-103",
    code: "PLN-[#090909]-ANNUAL",
    name: "GOR Platinum Atelier VIP Membership",
    interval: "Annual",
    price: 2800,
    currency: "USD",
    discountPercent: 30,
    status: "Active",
    activeSubscribersCount: 95,
    mrrValue: 22166,
    description: "Full-access annual VIP membership with unlimited free shipping, private fitting access, and bespoke drops.",
    features: [
      "Annual $3,500 store credit voucher",
      "48-hour Early Product Access before public launch",
      "30% Off All Store Items Year-Round",
      "Invites to Milan & London Lookbook Previews",
    ],
  },
  {
    id: "plan-104",
    code: "PLN-[#090909]-WEEKLY",
    name: "Fresh Essentials Weekly Rotation",
    interval: "Weekly",
    price: 85,
    currency: "USD",
    discountPercent: 15,
    status: "Active",
    activeSubscribersCount: 60,
    mrrValue: 20400,
    description: "Weekly rotation of organic heavyweight tees and loungewear essentials.",
    features: [
      "Weekly essentials rotation",
      "Pause/Resume anytime flexibility",
      "15% Off All Basic Items",
    ],
  },
  {
    id: "plan-105",
    code: "PLN-[#090909]-CUSTOM",
    name: "Corporate Executive Concierge Plan",
    interval: "Custom",
    price: 1500,
    currency: "USD",
    discountPercent: 20,
    status: "Active",
    activeSubscribersCount: 15,
    mrrValue: 22500,
    description: "Bespoke corporate membership for executive wardrobe management.",
    features: [
      "Custom billing & delivery intervals",
      "On-site tailor visits",
    ],
  },
];

export const INITIAL_MEMBERSHIP_TIERS = [
  {
    id: "tier-std",
    code: "TIER-STD",
    name: "Standard",
    colorHex: "#8E8A85",
    minSpendThreshold: 0,
    discountPercent: 5,
    freeShipping: false,
    earlyAccessHours: 0,
    exclusiveCollectionsAccess: false,
    prioritySupport: false,
    activeMembersCount: 1450,
  },
  {
    id: "tier-[#090909]",
    code: "TIER-SILVER",
    name: "Silver",
    colorHex: "#94a3b8",
    minSpendThreshold: 1500,
    discountPercent: 10,
    freeShipping: true,
    earlyAccessHours: 12,
    exclusiveCollectionsAccess: false,
    prioritySupport: false,
    activeMembersCount: 680,
  },
  {
    id: "tier-gold",
    code: "TIER-GOLD",
    name: "Gold",
    colorHex: "#C8A45D",
    minSpendThreshold: 5000,
    discountPercent: 20,
    freeShipping: true,
    earlyAccessHours: 24,
    exclusiveCollectionsAccess: true,
    prioritySupport: true,
    activeMembersCount: 320,
  },
  {
    id: "tier-plat",
    code: "TIER-PLATINUM",
    name: "Platinum",
    colorHex: "#e2e8f0",
    minSpendThreshold: 12000,
    discountPercent: 30,
    freeShipping: true,
    earlyAccessHours: 48,
    exclusiveCollectionsAccess: true,
    prioritySupport: true,
    activeMembersCount: 110,
  },
];

export const INITIAL_CUSTOMER_SUBSCRIPTIONS = [
  {
    id: "sub-901",
    subscriberCode: "SUB-ALX-01",
    customerName: "Alexander Vance",
    customerEmail: "alexander.vance@gormenswear.com",
    planId: "plan-101",
    planName: "Atelier Monthly Silk & Shirting Box",
    tier: "Platinum",
    mrrValue: 320,
    status: "Active",
    renewalDate: "2026-08-01",
    paymentStatus: "Paid",
    paymentMethod: "Visa **** 4242",
    shippingSchedule: "1st of Month",
    createdAt: "2026-01-10",
    billingHistory: [
      { date: "2026-07-01", amount: 320, status: "Paid", invoiceNo: "INV-2026-701" },
      { date: "2026-06-01", amount: 320, status: "Paid", invoiceNo: "INV-2026-601" },
    ],
  },
  {
    id: "sub-902",
    subscriberCode: "SUB-MAR-02",
    customerName: "Marcus Sterling",
    customerEmail: "m.sterling@luxurybrand.com",
    planId: "plan-102",
    planName: "Savile Wardrobe Quarterly Box",
    tier: "Gold",
    mrrValue: 283,
    status: "Active",
    renewalDate: "2026-08-15",
    paymentStatus: "Paid",
    paymentMethod: "Mastercard **** 8812",
    shippingSchedule: "15th of Month",
    createdAt: "2026-02-15",
    billingHistory: [
      { date: "2026-05-15", amount: 850, status: "Paid", invoiceNo: "INV-2026-515" },
    ],
  },
  {
    id: "sub-903",
    subscriberCode: "SUB-JUL-03",
    customerName: "Julian Thorne",
    customerEmail: "j.thorne@mayfairclub.co.uk",
    planId: "plan-103",
    planName: "GOR Platinum Atelier VIP Membership",
    tier: "Platinum",
    mrrValue: 233,
    status: "Active",
    renewalDate: "2027-01-10",
    paymentStatus: "Paid",
    paymentMethod: "Amex **** 1092",
    shippingSchedule: "1st of Month",
    createdAt: "2026-01-10",
    billingHistory: [
      { date: "2026-01-10", amount: 2800, status: "Paid", invoiceNo: "INV-2026-110" },
    ],
  },
  {
    id: "sub-904",
    subscriberCode: "SUB-DOM-04",
    customerName: "Dominic Croft",
    customerEmail: "d.croft@solaris.io",
    planId: "plan-104",
    planName: "Fresh Essentials Weekly Rotation",
    tier: "Silver",
    mrrValue: 340,
    status: "Paused",
    renewalDate: "2026-08-10",
    paymentStatus: "Pending",
    paymentMethod: "Visa **** 9901",
    shippingSchedule: "Weekly Mondays",
    createdAt: "2026-04-01",
    billingHistory: [
      { date: "2026-07-20", amount: 85, status: "Paid", invoiceNo: "INV-2026-720" },
    ],
  },
  {
    id: "sub-905",
    subscriberCode: "SUB-ELE-05",
    customerName: "Elena Rostova",
    customerEmail: "elena@rostovagroup.fr",
    planId: "plan-101",
    planName: "Atelier Monthly Silk & Shirting Box",
    tier: "Gold",
    mrrValue: 320,
    status: "Cancelled",
    renewalDate: "2026-07-15",
    paymentStatus: "Failed",
    paymentMethod: "Mastercard **** 3311",
    shippingSchedule: "15th of Month",
    createdAt: "2026-03-01",
    billingHistory: [
      { date: "2026-06-15", amount: 320, status: "Paid", invoiceNo: "INV-2026-615" },
    ],
  },
];

export const INITIAL_BENEFITS_RULES = [
  {
    id: "bnf-01",
    name: "Platinum Tier Storewide 30% Discount",
    type: "Percentage Discount",
    targetTier: "Platinum",
    value: "30%",
    status: "Active",
    description: "Automatic 30% discount applied to all retail items at checkout.",
  },
  {
    id: "bnf-02",
    name: "Gold & Platinum Free Worldwide Express Shipping",
    type: "Free Shipping",
    targetTier: "Gold",
    value: "$0 Express",
    status: "Active",
    description: "Complimentary DHL Express 2-day delivery on all member orders.",
  },
  {
    id: "bnf-[#090909]",
    name: "48-Hour Early Access to Lookbook Drops",
    type: "Early Product Access",
    targetTier: "Platinum",
    value: "48 Hours",
    status: "Active",
    description: "Private password-protected access to limited edition drops before public release.",
  },
  {
    id: "bnf-04",
    name: "Exclusive Private Collection Access",
    type: "Exclusive Collections",
    targetTier: "Gold",
    value: "Exclusive SKUs",
    status: "Active",
    description: "Unlocks member-only atelier jackets and silk shirting pieces.",
  },
];

export const INITIAL_SUBSCRIPTION_ANALYTICS = {
  mrr: "$192,866",
  arr: "$2,314,392",
  renewalRate: 94.2,
  churnRate: 2.1,
  activeSubscribers: 590,
  upcomingRenewals: 42,
  averageLTV: "$4,850",
  retentionCohort: [
    { month: "Month 1", retention: 100 },
    { month: "Month 3", retention: 96.5 },
    { month: "Month 6", retention: 94.2 },
    { month: "Month 12", retention: 91.8 },
  ],
};
