// GOR MENSWEAR — Enterprise Vendor & Marketplace Management Core Data & Utilities

export const INITIAL_VENDORS = [
  {
    id: "vnd-101",
    code: "VND-BIELLA-IT",
    companyName: "Biella Leatherworks Italy",
    contactPerson: "Matteo Rossini",
    email: "m.rossini@biella-leather.it",
    phone: "+39 015 882 100",
    taxId: "VAT-IT-98120491",
    verificationStatus: "Approved",
    commissionRate: 15,
    totalSales: 284500,
    activeProductsCount: 38,
    rating: 4.9,
    storeProfile: {
      description: "Artisanal Tuscan shearling and handcrafted suede outerwear atelier.",
      country: "Italy",
      city: "Biella, Piedmont",
      returnPolicy: "30-day luxury item returns",
      joinedDate: "2025-11-10",
    },
  },
  {
    id: "vnd-102",
    code: "VND-SAVILE-UK",
    companyName: "Savile Row Bespoke Tailors",
    contactPerson: "Arthur Pendelton",
    email: "a.pendelton@saviletailors.co.uk",
    phone: "+44 20 7946 0912",
    taxId: "GB-VND-4401928",
    verificationStatus: "Approved",
    commissionRate: 18,
    totalSales: 412000,
    activeProductsCount: 52,
    rating: 5.0,
    storeProfile: {
      description: "Mayfair bespoke suiting, pleated wool trousers, and British tailoring.",
      country: "United Kingdom",
      city: "London",
      returnPolicy: "Complimentary alteration & returns within 14 days",
      joinedDate: "2025-08-15",
    },
  },
  {
    id: "vnd-103",
    code: "VND-KYOTO-JP",
    companyName: "Kyoto Raw Silk Mills",
    contactPerson: "Kenji Takahashi",
    email: "kenji@kyotosilk.jp",
    phone: "+81 75 341 8800",
    taxId: "JP-TAX-7710293",
    verificationStatus: "Approved",
    commissionRate: 12,
    totalSales: 195000,
    activeProductsCount: 24,
    rating: 4.8,
    storeProfile: {
      description: "Hand-loomed raw silk grandad shirts and monogrammed kimono robes.",
      country: "Japan",
      city: "Kyoto",
      returnPolicy: "Unopened original packaging returns",
      joinedDate: "2026-01-20",
    },
  },
  {
    id: "vnd-104",
    code: "VND-GENEVA-CH",
    companyName: "Geneva Horology Atelier",
    contactPerson: "Henri Laurent",
    email: "h.laurent@genevahorology.ch",
    phone: "+41 22 710 9940",
    taxId: "CHE-114.920.102",
    verificationStatus: "Pending Review",
    commissionRate: 20,
    totalSales: 0,
    activeProductsCount: 8,
    rating: 4.7,
    storeProfile: {
      description: "Swiss handcrafted horological accessories and solid gold cufflinks.",
      country: "Switzerland",
      city: "Geneva",
      returnPolicy: "Insured courier returns",
      joinedDate: "2026-07-01",
    },
  },
  {
    id: "vnd-105",
    code: "VND-PARIS-FR",
    companyName: "Parisian Tweed House",
    contactPerson: "Claire Dubois",
    email: "claire@parisiantweed.fr",
    phone: "+33 1 42 68 55 00",
    taxId: "FR-VAT-33910283",
    verificationStatus: "Suspended",
    commissionRate: 15,
    totalSales: 45000,
    activeProductsCount: 12,
    rating: 3.9,
    storeProfile: {
      description: "Vintage French tweed blazers and tailored outerwear layers.",
      country: "France",
      city: "Paris",
      returnPolicy: "14-day standard return",
      joinedDate: "2026-02-10",
    },
  },
];

export const INITIAL_MARKETPLACE_PRODUCTS = [
  {
    id: "mprod-01",
    sku: "GOR-JKT-SUEDE-BIELLA",
    productName: "Biella Shearling Trimmed Suede Jacket",
    vendorId: "vnd-101",
    vendorName: "Biella Leatherworks Italy",
    price: 2450,
    commissionPercent: 15,
    approvalStatus: "Approved",
    stockLevel: 18,
    category: "Outerwear",
    type: "Vendor-owned",
    submittedDate: "2026-06-10",
  },
  {
    id: "mprod-02",
    sku: "GOR-TR-WOOL-SAVILE",
    productName: "Italian Merino Wool Pleated Trousers",
    vendorId: "vnd-102",
    vendorName: "Savile Row Bespoke Tailors",
    price: 580,
    commissionPercent: 18,
    approvalStatus: "Approved",
    stockLevel: 45,
    category: "Trousers",
    type: "Shared",
    submittedDate: "2026-06-12",
  },
  {
    id: "mprod-03",
    sku: "GOR-SH-SILK-KYOTO",
    productName: "Atelier Heavyweight Raw Silk Grandad Shirt",
    vendorId: "vnd-103",
    vendorName: "Kyoto Raw Silk Mills",
    price: 420,
    commissionPercent: 12,
    approvalStatus: "Approved",
    stockLevel: 32,
    category: "Shirts",
    type: "Marketplace",
    submittedDate: "2026-06-15",
  },
  {
    id: "mprod-04",
    sku: "GOR-CUFF-GOLD-GENEVA",
    productName: "Geneva Hand-Engraved Gold Cufflinks",
    vendorId: "vnd-104",
    vendorName: "Geneva Horology Atelier",
    price: 1250,
    commissionPercent: 20,
    approvalStatus: "Pending Review",
    stockLevel: 10,
    category: "Accessories",
    type: "Vendor-owned",
    submittedDate: "2026-07-20",
  },
  {
    id: "mprod-05",
    sku: "GOR-BLZ-TWEED-PARIS",
    productName: "Parisian Heritage Tweed Double-Breasted Blazer",
    vendorId: "vnd-105",
    vendorName: "Parisian Tweed House",
    price: 1650,
    commissionPercent: 15,
    approvalStatus: "Rejected",
    stockLevel: 5,
    category: "Blazers",
    type: "Marketplace",
    submittedDate: "2026-07-22",
  },
];

export const INITIAL_MARKETPLACE_ORDERS = [
  {
    id: "mord-801",
    orderId: "ORD-MKT-2026-101",
    vendorId: "vnd-101",
    vendorName: "Biella Leatherworks Italy",
    orderDate: "2026-07-25",
    customerName: "Lord Julian Sterling",
    totalAmount: 2450,
    commissionAmount: 367.5,
    netVendorPayout: 2082.5,
    fulfillmentStatus: "Fulfilled",
    shipmentStatus: "Delivered",
    returnRequest: false,
  },
  {
    id: "mord-802",
    orderId: "ORD-MKT-2026-102",
    vendorId: "vnd-102",
    vendorName: "Savile Row Bespoke Tailors",
    orderDate: "2026-07-26",
    customerName: "Dominic Thorne",
    totalAmount: 1160,
    commissionAmount: 208.8,
    netVendorPayout: 951.2,
    fulfillmentStatus: "Processing",
    shipmentStatus: "In Transit",
    returnRequest: false,
  },
  {
    id: "mord-803",
    orderId: "ORD-MKT-2026-103",
    vendorId: "vnd-103",
    vendorName: "Kyoto Raw Silk Mills",
    orderDate: "2026-07-27",
    customerName: "Alexander Vance",
    totalAmount: 840,
    commissionAmount: 100.8,
    netVendorPayout: 739.2,
    fulfillmentStatus: "Unfulfilled",
    shipmentStatus: "Preparing",
    returnRequest: true,
  },
];

export const INITIAL_VENDOR_PAYOUTS = [
  {
    id: "pay-501",
    payoutCode: "PAY-2026-07A",
    vendorId: "vnd-101",
    vendorName: "Biella Leatherworks Italy",
    period: "July 2026 (Period 1)",
    grossRevenue: 85000,
    commissionDeducted: 12750,
    netPayoutAmount: 72250,
    status: "Paid",
    paymentMethod: "Bank Wire Transfer (SWIFT)",
    processedDate: "2026-07-15",
  },
  {
    id: "pay-502",
    payoutCode: "PAY-2026-07B",
    vendorId: "vnd-102",
    vendorName: "Savile Row Bespoke Tailors",
    period: "July 2026 (Period 1)",
    grossRevenue: 120000,
    commissionDeducted: 21600,
    netPayoutAmount: 98400,
    status: "Pending",
    paymentMethod: "ACH Direct Deposit",
    processedDate: "2026-07-30",
  },
  {
    id: "pay-503",
    payoutCode: "PAY-2026-07C",
    vendorId: "vnd-103",
    vendorName: "Kyoto Raw Silk Mills",
    period: "July 2026 (Period 1)",
    grossRevenue: 48000,
    commissionDeducted: 5760,
    netPayoutAmount: 42240,
    status: "Processing",
    paymentMethod: "PayPal Corporate",
    processedDate: "2026-07-28",
  },
];

export const INITIAL_MARKETPLACE_RULES = {
  defaultCommissionPercent: 15,
  productApprovalRequired: true,
  autoPublishApprovedVendors: false,
  vendorProductLimit: 500,
  manualReviewPriceThreshold: 2000,
  payoutScheduleInterval: "Bi-Weekly",
};

export const INITIAL_MARKETPLACE_ANALYTICS = {
  totalMarketplaceRevenue: "$936,500",
  totalCommissionRevenue: "$145,210",
  totalMarketplaceOrdersCount: 420,
  topVendors: [
    { name: "Savile Row Bespoke Tailors", revenue: "$412,000", commission: "$74,160", share: 44 },
    { name: "Biella Leatherworks Italy", revenue: "$284,500", commission: "$42,675", share: 30 },
    { name: "Kyoto Raw Silk Mills", revenue: "$195,000", commission: "$23,400", share: 21 },
    { name: "Parisian Tweed House", revenue: "$45,000", commission: "$6,750", share: 5 },
  ],
  vendorPerformanceScore: 96.4,
};
