// GOR MENSWEAR — Enterprise WMS (Warehouse & Inventory Operations) Core Data & Utilities

export const INITIAL_WAREHOUSES = [
  {
    id: "wh-01",
    name: "Milan Central Logistics Atelier",
    code: "MIL-ATL-01",
    status: "Active",
    type: "Primary Fulfillment",
    manager: {
      name: "Gianluigi Vettori",
      email: "g.vettori@gormenswear.com",
      phone: "+39 02 8940 1200",
    },
    address: {
      street: "Via Montenapoleone 18",
      city: "Milan",
      region: "Lombardy",
      country: "Italy",
      zip: "20121",
    },
    capacitySqFt: 45000,
    totalBins: 1200,
    spaceUtilization: 78,
    stockCount: 8450,
    reservedCount: 420,
    incomingCount: 1200,
    lastAudit: "2026-07-20",
  },
  {
    id: "wh-02",
    name: "London Mayfair Flagship Hub",
    code: "LDN-MAY-02",
    status: "Active",
    type: "Regional Hub & Storefront",
    manager: {
      name: "Alistair Thorne",
      email: "a.thorne@gormenswear.com",
      phone: "+44 20 7946 0912",
    },
    address: {
      street: "24 Savile Row",
      city: "London",
      region: "Greater London",
      country: "United Kingdom",
      zip: "W1S 3PR",
    },
    capacitySqFt: 22000,
    totalBins: 650,
    spaceUtilization: 84,
    stockCount: 4120,
    reservedCount: 310,
    incomingCount: 450,
    lastAudit: "2026-07-15",
  },
  {
    id: "wh-03",
    name: "New York SoHo Atelier Depot",
    code: "NYC-SOHO-03",
    status: "Active",
    type: "North America Hub",
    manager: {
      name: "Marcus Sterling",
      email: "m.sterling@gormenswear.com",
      phone: "+1 212 555 0198",
    },
    address: {
      street: "112 Mercer Street",
      city: "New York",
      region: "NY",
      country: "United States",
      zip: "10012",
    },
    capacitySqFt: 35000,
    totalBins: 950,
    spaceUtilization: 65,
    stockCount: 6100,
    reservedCount: 580,
    incomingCount: 800,
    lastAudit: "2026-07-22",
  },
  {
    id: "wh-04",
    name: "Tokyo Ginza Reserve Storehouse",
    code: "TYO-GIN-04",
    status: "Maintenance",
    type: "APAC Regional Depot",
    manager: {
      name: "Kenji Sato",
      email: "k.sato@gormenswear.com",
      phone: "+81 3 5555 0143",
    },
    address: {
      street: "6-10-1 Ginza, Chuo-ku",
      city: "Tokyo",
      region: "Kanto",
      country: "Japan",
      zip: "104-0061",
    },
    capacitySqFt: 18000,
    totalBins: 500,
    spaceUtilization: 42,
    stockCount: 1950,
    reservedCount: 45,
    incomingCount: 0,
    lastAudit: "2026-07-01",
  },
];

export const INITIAL_INVENTORY = [
  {
    id: "inv-01",
    sku: "GOR-CO-ALO-BUR-M",
    productName: "GOR Alo Burgundy Heavyweight Co-Ord",
    category: "Co-Ord Sets",
    warehouseId: "wh-01",
    warehouseName: "Milan Central Logistics Atelier",
    unitCost: 160,
    unitPrice: 380,
    currentStock: 145,
    reservedStock: 18,
    availableStock: 127, // Current - Reserved
    incomingStock: 50,
    damagedStock: 2,
    safetyStock: 30,
    reorderPoint: 40,
    maxStockLevel: 300,
    locationBin: "A1-04-12",
    lastRestocked: "2026-07-18",
    status: "In Stock",
  },
  {
    id: "inv-02",
    sku: "GOR-CO-PRD-SAN-L",
    productName: "Prada Desert Sand Textured Zip Set",
    category: "Co-Ord Sets",
    warehouseId: "wh-01",
    warehouseName: "Milan Central Logistics Atelier",
    unitCost: 210,
    unitPrice: 520,
    currentStock: 12,
    reservedStock: 8,
    availableStock: 4,
    incomingStock: 100,
    damagedStock: 0,
    safetyStock: 15,
    reorderPoint: 20,
    maxStockLevel: 150,
    locationBin: "A2-01-05",
    lastRestocked: "2026-06-25",
    status: "Low Stock",
  },
  {
    id: "inv-03",
    sku: "GOR-SH-TEE-BLK-L",
    productName: "GOR Classic Heavyweight Oversized Tee",
    category: "Shirts",
    warehouseId: "wh-02",
    warehouseName: "London Mayfair Flagship Hub",
    unitCost: 65,
    unitPrice: 180,
    currentStock: 280,
    reservedStock: 35,
    availableStock: 245,
    incomingStock: 150,
    damagedStock: 5,
    safetyStock: 50,
    reorderPoint: 75,
    maxStockLevel: 500,
    locationBin: "B3-12-08",
    lastRestocked: "2026-07-22",
    status: "In Stock",
  },
  {
    id: "inv-04",
    sku: "GOR-TR-ONYX-PLE-32",
    productName: "Structured Tailored Trousers in Onyx",
    category: "Trousers",
    warehouseId: "wh-03",
    warehouseName: "New York SoHo Atelier Depot",
    unitCost: 110,
    unitPrice: 290,
    currentStock: 0,
    reservedStock: 0,
    availableStock: 0,
    incomingStock: 200,
    damagedStock: 1,
    safetyStock: 25,
    reorderPoint: 30,
    maxStockLevel: 200,
    locationBin: "C1-09-03",
    lastRestocked: "2026-05-14",
    status: "Out of Stock",
  },
  {
    id: "inv-05",
    sku: "GOR-JK-SHR-AVI-XL",
    productName: "Luxury Shearling Collar Aviator Jacket",
    category: "Outerwear",
    warehouseId: "wh-01",
    warehouseName: "Milan Central Logistics Atelier",
    unitCost: 420,
    unitPrice: 950,
    currentStock: 18,
    reservedStock: 12,
    availableStock: 6,
    incomingStock: 40,
    damagedStock: 0,
    safetyStock: 10,
    reorderPoint: 15,
    maxStockLevel: 80,
    locationBin: "OUT-08-01",
    lastRestocked: "2026-07-10",
    status: "Low Stock",
  },
  {
    id: "inv-06",
    sku: "GOR-BL-SAV-NAV-M",
    productName: "Savile Double-Breasted Cashmere Blazer",
    category: "Outerwear",
    warehouseId: "wh-02",
    warehouseName: "London Mayfair Flagship Hub",
    unitCost: 650,
    unitPrice: 1450,
    currentStock: 45,
    reservedStock: 5,
    availableStock: 40,
    incomingStock: 25,
    damagedStock: 1,
    safetyStock: 15,
    reorderPoint: 20,
    maxStockLevel: 100,
    locationBin: "SAV-01-02",
    lastRestocked: "2026-07-24",
    status: "In Stock",
  },
  {
    id: "inv-07",
    sku: "GOR-SH-SILK-IVR-L",
    productName: "Atelier Raw Silk Grandad Shirt",
    category: "Shirts",
    warehouseId: "wh-03",
    warehouseName: "New York SoHo Atelier Depot",
    unitCost: 180,
    unitPrice: 420,
    currentStock: 160,
    reservedStock: 20,
    availableStock: 140,
    incomingStock: 0,
    damagedStock: 0,
    safetyStock: 30,
    reorderPoint: 40,
    maxStockLevel: 120,
    locationBin: "SLK-04-09",
    lastRestocked: "2026-07-02",
    status: "Overstock",
  },
];

export const INITIAL_MOVEMENTS = [
  {
    id: "mov-8901",
    date: "2026-07-27 14:30",
    sku: "GOR-CO-ALO-BUR-M",
    productName: "GOR Alo Burgundy Heavyweight Co-Ord",
    type: "Stock In",
    quantity: 50,
    fromWarehouse: "Supplier Delivery (Biella Mills)",
    toWarehouse: "Milan Central Logistics Atelier",
    performedBy: "Gianluigi Vettori",
    referenceNo: "PO-2026-901",
    reason: "Purchase Order Fulfillment",
    notes: "Batch #44-A passed quality audit",
  },
  {
    id: "mov-8902",
    date: "2026-07-26 11:15",
    sku: "GOR-CO-PRD-SAN-L",
    productName: "Prada Desert Sand Textured Zip Set",
    type: "Stock Transfer",
    quantity: 20,
    fromWarehouse: "Milan Central Logistics Atelier",
    toWarehouse: "London Mayfair Flagship Hub",
    performedBy: "Alistair Thorne",
    referenceNo: "TRF-2026-104",
    reason: "Flagship Rebalancing",
    notes: "Transferred via express courier",
  },
  {
    id: "mov-8903",
    date: "2026-07-25 09:40",
    sku: "GOR-TR-ONYX-PLE-32",
    productName: "Structured Tailored Trousers in Onyx",
    type: "Stock Out",
    quantity: 30,
    fromWarehouse: "New York SoHo Atelier Depot",
    toWarehouse: "Customer Orders (Batch Delivery)",
    performedBy: "Marcus Sterling",
    referenceNo: "ORD-GOR-892401",
    reason: "Order Fulfillment",
    notes: "Fulfilling pre-orders",
  },
  {
    id: "mov-8904",
    date: "2026-07-24 16:20",
    sku: "GOR-SH-TEE-BLK-L",
    productName: "GOR Classic Heavyweight Oversized Tee",
    type: "Manual Adjustment",
    quantity: -5,
    fromWarehouse: "London Mayfair Flagship Hub",
    toWarehouse: "N/A",
    performedBy: "Alistair Thorne",
    referenceNo: "ADJ-2026-044",
    reason: "Discrepancy Audit",
    notes: "Corrected physical count vs system log",
  },
  {
    id: "mov-8905",
    date: "2026-07-23 13:05",
    sku: "GOR-JK-SHR-AVI-XL",
    productName: "Luxury Shearling Collar Aviator Jacket",
    type: "Damage Report",
    quantity: -2,
    fromWarehouse: "Milan Central Logistics Atelier",
    toWarehouse: "Quarantine Bin D",
    performedBy: "Gianluigi Vettori",
    referenceNo: "DMG-2026-012",
    reason: "Transit Damage",
    notes: "Zipper snagged during pallet inspection",
  },
  {
    id: "mov-8906",
    date: "2026-07-22 10:00",
    sku: "GOR-SH-SILK-IVR-L",
    productName: "Atelier Raw Silk Grandad Shirt",
    type: "Return Stock",
    quantity: 4,
    fromWarehouse: "Customer Returns Depot",
    toWarehouse: "New York SoHo Atelier Depot",
    performedBy: "Marcus Sterling",
    referenceNo: "RET-GOR-7712",
    reason: "Customer Size Exchange",
    notes: "Inspected & approved for restocking",
  },
];

export const INITIAL_PURCHASE_ORDERS = [
  {
    id: "po-101",
    poNumber: "PO-2026-901",
    supplierId: "sup-01",
    supplierName: "Biella Woolens & Cashmere SpA",
    expectedDate: "2026-08-05",
    destinationWarehouseId: "wh-01",
    destinationWarehouseName: "Milan Central Logistics Atelier",
    status: "Issued",
    totalAmount: 48000,
    createdAt: "2026-07-20",
    notes: "High density raw silk and cashmeres for Autumn drop.",
    items: [
      { sku: "GOR-CO-ALO-BUR-M", name: "GOR Alo Burgundy Heavyweight Co-Ord", orderQty: 150, receivedQty: 50, unitCost: 160 },
      { sku: "GOR-BL-SAV-NAV-M", name: "Savile Double-Breasted Cashmere Blazer", orderQty: 40, receivedQty: 0, unitCost: 600 },
    ],
    receivingLogs: [
      { date: "2026-07-27", qty: 50, batch: "B-2026-01", receivedBy: "Gianluigi Vettori" }
    ],
  },
  {
    id: "po-102",
    poNumber: "PO-2026-902",
    supplierId: "sup-02",
    supplierName: "Tessitura Monti Silk Mills",
    expectedDate: "2026-08-12",
    destinationWarehouseId: "wh-03",
    destinationWarehouseName: "New York SoHo Atelier Depot",
    status: "Receiving",
    totalAmount: 32000,
    createdAt: "2026-07-15",
    notes: "Rush restock for Structured Onyx Trousers.",
    items: [
      { sku: "GOR-TR-ONYX-PLE-32", name: "Structured Tailored Trousers in Onyx", orderQty: 200, receivedQty: 100, unitCost: 110 },
      { sku: "GOR-SH-SILK-IVR-L", name: "Atelier Raw Silk Grandad Shirt", orderQty: 100, receivedQty: 100, unitCost: 210 },
    ],
    receivingLogs: [
      { date: "2026-07-25", qty: 200, batch: "B-2026-02", receivedBy: "Marcus Sterling" }
    ],
  },
  {
    id: "po-103",
    poNumber: "PO-2026-903",
    supplierId: "sup-03",
    supplierName: "Savile Row Craftsmanship Co.",
    expectedDate: "2026-08-20",
    destinationWarehouseId: "wh-02",
    destinationWarehouseName: "London Mayfair Flagship Hub",
    status: "Draft",
    totalAmount: 18500,
    createdAt: "2026-07-26",
    notes: "Bespoke outerwear and leather trim accessories.",
    items: [
      { sku: "GOR-JK-SHR-AVI-XL", name: "Luxury Shearling Collar Aviator Jacket", orderQty: 30, receivedQty: 0, unitCost: 420 },
    ],
    receivingLogs: [],
  },
  {
    id: "po-104",
    poNumber: "PO-2026-880",
    supplierId: "sup-04",
    supplierName: "Como Mulberry Silk Atelier",
    expectedDate: "2026-07-10",
    destinationWarehouseId: "wh-01",
    destinationWarehouseName: "Milan Central Logistics Atelier",
    status: "Completed",
    totalAmount: 54000,
    createdAt: "2026-06-15",
    notes: "Summer Silk Collection completed shipment.",
    items: [
      { sku: "GOR-SH-TEE-BLK-L", name: "GOR Classic Heavyweight Oversized Tee", orderQty: 500, receivedQty: 500, unitCost: 65 },
    ],
    receivingLogs: [
      { date: "2026-07-10", qty: 500, batch: "B-2026-00", receivedBy: "Gianluigi Vettori" }
    ],
  },
];

export const INITIAL_SUPPLIERS = [
  {
    id: "sup-01",
    code: "SUP-BIE-01",
    name: "Biella Woolens & Cashmere SpA",
    contactPerson: "Matteo Rossi",
    email: "m.rossi@biella-textiles.it",
    phone: "+39 015 849 2000",
    address: "Via Torino 45, Biella, Italy",
    leadTimeDays: 14,
    preferred: true,
    rating: 4.9,
    onTimeDeliveryRate: 98.5,
    qualityScore: 99.2,
    totalPOs: 24,
    totalSpend: 420000,
  },
  {
    id: "sup-02",
    code: "SUP-MON-02",
    name: "Tessitura Monti Silk Mills",
    contactPerson: "Francesca Monti",
    email: "orders@montisilk.it",
    phone: "+39 0422 831 100",
    address: "Maserada sul Piave, Treviso, Italy",
    leadTimeDays: 10,
    preferred: true,
    rating: 4.8,
    onTimeDeliveryRate: 96.0,
    qualityScore: 98.0,
    totalPOs: 18,
    totalSpend: 295000,
  },
  {
    id: "sup-03",
    code: "SUP-SAV-03",
    name: "Savile Row Craftsmanship Co.",
    contactPerson: "Charles Kingsman",
    email: "c.kingsman@savilerowcraft.co.uk",
    phone: "+44 20 7946 0555",
    address: "15 Savile Row, London, UK",
    leadTimeDays: 21,
    preferred: false,
    rating: 4.6,
    onTimeDeliveryRate: 92.4,
    qualityScore: 97.5,
    totalPOs: 12,
    totalSpend: 180000,
  },
  {
    id: "sup-04",
    code: "SUP-COM-04",
    name: "Como Mulberry Silk Atelier",
    contactPerson: "Isabella De Luca",
    email: "isabella@comosilkatelier.com",
    phone: "+39 031 520 890",
    address: "Via Bellagio 12, Como, Italy",
    leadTimeDays: 7,
    preferred: true,
    rating: 5.0,
    onTimeDeliveryRate: 99.8,
    qualityScore: 99.9,
    totalPOs: 31,
    totalSpend: 560000,
  },
];

export const INITIAL_ALERTS_CONFIG = {
  lowStockThreshold: 15,
  overstockThreshold: 150,
  reorderPointDefault: 30,
  expiryWarningDays: 90,
  autoGeneratePO: false,
  emailNotifications: true,
  activeAlerts: [
    { id: "alt-1", type: "Low Stock", sku: "GOR-CO-PRD-SAN-L", message: "Only 4 units available in Milan Atelier (Reorder Point: 20)", level: "warning" },
    { id: "alt-2", type: "Out of Stock", sku: "GOR-TR-ONYX-PLE-32", message: "Structured Onyx Trousers out of stock in NYC SoHo Depot", level: "critical" },
    { id: "alt-3", type: "Overstock", sku: "GOR-SH-SILK-IVR-L", message: "Raw Silk Shirt stock (160) exceeds max threshold (120)", level: "info" },
    { id: "alt-4", type: "Reorder Point Triggered", sku: "GOR-JK-SHR-AVI-XL", message: "Available stock (6) reached safety threshold", level: "warning" },
  ],
};

export const INITIAL_REPORTS = {
  valuation: {
    totalValue: "$1,842,950",
    fifoValuation: "$1,865,000",
    lifoValuation: "$1,820,400",
    weightedAvgValuation: "$1,842,950",
    categoryBreakdown: [
      { category: "Outerwear & Coats", value: "$780,000", percentage: 42.3 },
      { category: "Co-Ord Sets", value: "$415,000", percentage: 22.5 },
      { category: "Shirts & Silk", value: "$390,000", percentage: 21.2 },
      { category: "Trousers", value: "$257,950", percentage: 14.0 },
    ],
  },
  turnover: {
    annualTurnoverRatio: 4.8,
    daysInventoryOutstanding: 76,
    industryBenchmarkRatio: 3.5,
    topTurningCategory: "Co-Ord Sets (6.2x)",
  },
  stockAging: [
    { ageGroup: "0 - 30 Days", count: 12400, value: "$1,150,000", percent: 62.4 },
    { ageGroup: "31 - 60 Days", count: 4800, value: "$450,000", percent: 24.4 },
    { ageGroup: "61 - 90 Days", count: 2100, value: "$180,000", percent: 9.8 },
    { ageGroup: "90+ Days", count: 820, value: "$62,950", percent: 3.4 },
  ],
  warehousePerformance: [
    { name: "Milan Central Atelier", fulfillmentSpeedHours: 4.2, stockAccuracy: 99.4, spaceUtil: "78%" },
    { name: "London Mayfair Hub", fulfillmentSpeedHours: 3.8, stockAccuracy: 98.9, spaceUtil: "84%" },
    { name: "New York SoHo Depot", fulfillmentSpeedHours: 5.1, stockAccuracy: 98.2, spaceUtil: "65%" },
    { name: "Tokyo Ginza Storehouse", fulfillmentSpeedHours: 6.5, stockAccuracy: 97.5, spaceUtil: "42%" },
  ],
};
